# ENVS
#conda snakemake = for running snakemake
#Rscript ... = default R env, which runs normally. need to package up
#     collate all R packages/versions?...   
#conda Increate22 = generic Py scRNA env
#conda tcrdist3_env = specific for tcrdist3 work

rule import_data:
    output:
        "data/import/dataDescription.xlsx"
        "data/import/metadata-donor.csv"
        "data/import/panImmune.h5ad"
        "data/import/Tcell-scTCR.csv"
        "data/import/Tcell.h5ad"
    shell:
        "/Users/kaneucl/miniconda3/envs/R-4.2.3/bin/Rscript scr/import.R"

rule process_imported_data:
    input:
        "data/import/metadata-donor.csv"
        "data/import/panImmune.h5ad"
        "data/import/Tcell.h5ad"
        "../resources/markers.csv"
    output:
        "data/panImm_obs.csv"
        "data/import/PC.h5ad"
        "data/panImm_exp.csv"
        "data/Tcell_obs.csv"
        "data/Tcell_exp.csv"
    shell:
        "/Users/kaneucl/miniconda3/envs/Increate22/bin/python scr/process.py"

rule abundance_prep:
    input:
        "data/panImm_obs.csv"
        "data/Tcell_obs.csv"
        "data/validation_obs.csv" 
    output:
        "data/comp.RData"
        "data/ords.RData"
    shell:
        "Rscript scr/abundances.R"

rule PC_Ig:
    input:
        "data/import/PC.h5ad"
    output:
        "data/mPC_id.csv"
    shell:
        "/Users/kaneucl/miniconda3/envs/Increate22/bin/python scr/PC_Ig.py"

rule PC_analysis:
    input:
        "/data/import/PC.h5ad"
        "data/mPC_id.csv"
        "../resources/pathways.csv"
        "data/import/metadata-donor.csv"
    output:
        "data/tumour_modules_scr.RData"
        "data/tumour_modules_pct.csv"
        "data/tumour_DE.csv"
        "data/tumour_DE_fgsea.RData"
    shell:
        "Rscript scr/PC_analysis.R"

rule abundance_testing:
    input:
        "data/comp.RData"
        "data/ords.RData"
    output:
        "data/da_results.RData"
    shell:
        "Rscript scr/da_res.R"

rule tcr_clustering:
    input:
        "data/import/Tcell-scTCR.csv"
    output:
        "data/tcr_clustering.csv"
    shell:
        "/Users/kaneucl/miniconda3/envs/tcrdist3_env/bin/python3.8 scr/tcr_clustering.py"

rule tcr_analysis:
    input:
        "data/import/Tcell-scTCR.csv"
        "data/Tcell_obs.csv"
    output:
        "data/tcr_analysis.RData"
    shell:
        "Rscript scr/tcr_analysis.R"

rule tcell_tumour:
    input:
        ""
    output:
        ""
    shell:
        "Rscript scr/tcell_tumour_associations.R"
