---
title: "4"
output:
  html_document:
    code_folding: hide
    toc: true # table of content true
    toc_depth: 3  # upto three depths of headings (specified by #, ## and ###)
    number_sections: false  ## if you want number sections at each table header
params:
    args: myarg
---

## Setup

```{r eval=T, hide=T}
library(tidyverse)
library(ggpubr)
library(RColorBrewer)
library(viridis)
source('../resources/aes.R')
range01 <- function(x){(x-min(x))/(max(x)-min(x))}
load(file = '../preprocessing/data/comp.RData')
load(file = '../preprocessing/data/ords.RData')
load(file = '../preprocessing/data/tcr_analysis.RData')
obs = read.csv('../preprocessing/data/Tcell_obs.csv')
tcr = read.csv('../preprocessing/data/import/Tcell-scTCR.csv')
donor_md = read.csv('../preprocessing/data/import/metadata-donor.csv')
dir.create('../figures/4')
```

## 4A

```{r fig.height=2.5, fig.width=2.5}

th = theme(legend.position = "none",
  plot.title = element_text(hjust = 0.5, size=12),
  axis.text.x = element_text(size=11),axis.title.x = element_text(size=13),
  axis.text.y = element_text(size=11),axis.title.y = element_text(size=13))

div = tcr_analysis$clonality %>% 
  mutate(cohort = replace(cohort, cohort=='MGUS', 'SMM')) %>% 
  filter(! donor_id %in% donors.longit)

#all T cells
div %>% filter(cohort!='Non',group=='all') %>% 
  left_join(ords$Tcell$PCA %>% 
    left_join(comp$Tcell %>% select(sample_id,donor_id) %>% distinct())) %>% 
  ggplot(aes(PC1*-1, clon))+geom_point(size=1.5, aes(color=cohort))+
  geom_smooth(method='lm',size=1,alpha=0.2, color='grey20')+
  ggpubr::stat_cor(label.sep='\n', label.y= -1.25)+
  scale_color_manual(values=diagnosis_col)+scale_fill_manual(values=diagnosis_col)+
  labs(x='PC1',y='Clonality',title='All T cells')+theme_classic()+th-> pl
pl
ggsave(plot=pl,filename = '../figures/4/A-left.pdf',width=2.5,height=2.5, dpi="retina")

#CD8+Tm
div %>% filter(cohort!='Non',group=='CD8.Tm') %>% 
  left_join(ords$Tcell$PCA %>% 
    left_join(comp$Tcell %>% select(sample_id,donor_id) %>% distinct())) %>% 
  ggplot(aes(PC1*-1,clon))+geom_point(size=1, aes(color=cohort))+
  geom_smooth(method='lm',size=1,alpha=0.2, color='grey20')+
  ggpubr::stat_cor(label.sep='\n',label.x= -0.05, label.y = -0.75)+
  scale_color_manual(values=diagnosis_col)+scale_fill_manual(values=diagnosis_col)+
  labs(x='PC1',y='Clonality',title='CD8+ memory')+theme_classic()+th-> pl
pl
ggsave(plot=pl,filename = '../figures/4/A-right.pdf',width=2.5,height=2.5, dpi="retina")

```

## 4B

clonality, CD8.Tm
```{r fig.width=1.6, fig.height=3}
div = tcr_analysis$clonality %>% 
  filter(! donor_id %in% donors.longit, cohort!='MGUS')
  
#CD8+Tm
dat = div %>% mutate(diagnosis=cohort) %>% 
  filter(group=='CD8.Tm') %>% 
  mutate(diagnosis=factor(diagnosis,c('Non','SMM','MM')))

dat %>% 
  ggplot(aes(diagnosis,clon,fill=diagnosis))+
  geom_boxplot(outlier.alpha = 0)+
  geom_jitter(width=0.2,height=0,size=0.2)+
  ggpubr::stat_compare_means(
    comparisons = list(c('Non','SMM'),c('Non','MM')),
  method = 'wilcox.test',size=3.5)+
  scale_fill_manual(values=diagnosis_col)+
  labs(y='Clonality',title='CD8+ memory')+
  #ylim(c(-2.7,-0.2))+
  theme_classic()+
  theme(
    legend.position = "none",
    plot.title = element_text(hjust = 0.5, size=12),
    axis.title.x = element_blank(), 
    axis.text.x = element_text(angle = 45, vjust = 1, hjust=1, size=11),
    axis.title.y = element_text(size=13), 
    axis.text.y = element_text(size=11)
  )-> pl
pl
ggsave(plot=pl, filename='../figures/4/B.pdf',width=1.6,height=3, dpi="retina")


dat %>% 
  ggplot(aes(diagnosis,n1/counts*100,fill=diagnosis))+
  geom_boxplot(outlier.alpha = 0)+
  geom_jitter(width=0.2,height=0,size=0.2)+
  ggpubr::stat_compare_means(
    comparisons = list(c('Non','SMM'),c('Non','MM')),
  method = 'wilcox.test',size=3.5)+
  scale_fill_manual(values=diagnosis_col)+
  labs(y='% single',title='CD8+ memory')+
  #ylim(c(-2.7,-0.2))+
  theme_classic()+
  theme(
    legend.position = "none",
    plot.title = element_text(hjust = 0.5, size=12),
    axis.title.x = element_blank(), 
    axis.text.x = element_text(angle = 45, vjust = 1, hjust=1, size=11),
    axis.title.y = element_text(size=13), 
    axis.text.y = element_text(size=11)
  )-> pl
pl
ggsave(plot=pl, filename='../figures/4/B-pct1.pdf',width=1.6,height=3, dpi="retina")

```

## 4C

```{r}
# Example network plots

library(igraph)
library(ggraph)
graph_from_clone2clus = function(input,attach_col=c()){

  nodes = unique(input$clone_id)
  groups = input$clus_id %>% .[!is.na(.)]

  # Initialize an empty graph
  g <- graph.empty(n = length(nodes),directed = F)

  # Add nodes from the 'samples' column
  V(g)$name <- nodes

  if ( !length(attach_col)==0 ){
    for ( col in attach_col){ V(g)[[col]] = input[[col]] }
  }

  # Add edges between samples within the same group
  for (group in unique(groups)) {
    samples_in_group <- input$clone_id[(input$clus_id == group) & (!is.na(input$clus_id))]
    if ( length(samples_in_group)==1){next}
    edges <- combn(samples_in_group, 2)
    g = add_edges(g, t(edges))
  }

  # Remove self-loops
  g <- delete.edges(g, which(ends(g, E(g))[,1] == ends(g, E(g))[,2]))

  return(g)
}

donors_pl = c('Maura_2023.PT85','Foster_2024.SMM10')
for ( i in donors_pl ){

dat = as_tibble(obs) %>% select(clone_id,donor_id) %>% distinct() %>% 
  filter(donor_id==i, clone_id!='',!is.na(clone_id)) %>%
  filter(clone_id %in% tcr[tcr$clone_size>1,]$clone_id) %>% 
  left_join(tcr_analysis$clus$clon_clus)

print(i)
print(round(sum(!is.na(dat$clus_id))/dim(dat)[1],3)*100)

dat %>% 
  graph_from_clone2clus() %>%
  ggraph(layout = 'fr')+geom_edge_link()+geom_node_point(size=1.5)+
  coord_fixed()+
  theme_void()+theme(plot.title = element_text(hjust = 0.5, size=14))->pl
print(pl)
ggsave(plot=pl,filename = paste0('../figures/4/C-',i,'.pdf'),width=2.5,height=2.5, dpi="retina")

}
```

## 4D

```{r fig.width=1.25, fig.height=3}
clustered = tcr_analysis$clus[['pct']] %>% mutate(diagnosis=cohort)

psuedo0 = min(clustered$clustered[clustered$clustered>0])

clustered %>% filter(diagnosis!='MGUS') %>% 
  mutate(diagnosis=factor(diagnosis,c('SMM','MM'))) %>% 
  ggplot(aes(diagnosis,log10(clustered+psuedo0),fill=diagnosis))+
  geom_boxplot(outlier.alpha = 0)+
  geom_jitter(width=0.2,height=0,size=0.4)+
  ggpubr::stat_compare_means(comparisons = list(c('SMM','MM')),
  method = 'wilcox.test',size=3.5)+
  #scale_y_log10(limits=c(1,65),breaks=c(1,10))+
  #scale_y_continuous(limits=c(0,42.5),breaks=c(0,10,20,30,40))+
  scale_y_continuous(breaks=c(0,1,log10(50)), limits=c(0,log10(50)+0.1), labels=c(1,10,50))+
  annotation_logticks(sides='l',short=unit(0.1,'cm'),mid=unit(0.1,'cm'),long=unit(0.1,'cm'))+
  scale_fill_manual(values=diagnosis_col)+
  labs(y='% expanded repertoire clustered',title='')+
  theme_classic()+
  theme(
    legend.position = "none",
    plot.title = element_text(hjust = 0.5, size=12),
    axis.title.x = element_blank(), 
    axis.text.x = element_text(angle = 45, vjust = 1, hjust=1, size=11),
    axis.title.y = element_text(size=11), 
    axis.text.y = element_text(size=11)
  )-> pl
pl

ggsave(plot=pl, filename='../figures/4/D-left.pdf',width=1.25,height=3, dpi="retina")
```


```{r fig.width=3, fig.height=3}

clustered %>% 
  left_join(ords$Tcell$PCA %>% 
              left_join(comp$Tcell %>% select(sample_id,donor_id) %>% distinct())) %>% 
  filter(log10(clustered+psuedo0)>0.3) %>% 
  ggplot(aes(PC1*-1, clustered+psuedo0))+
  scale_y_log10()+
  annotation_logticks(sides='l',short=unit(0.1,'cm'),mid=unit(0.1,'cm'),long=unit(0.1,'cm'))+
  geom_point(aes(color=diagnosis), size=1.5)+
  geom_smooth(method='lm',size=1,alpha=0.2, color='grey20')+
  ggpubr::stat_cor(label.sep='\n')+
  scale_color_manual(values=diagnosis_col)+scale_fill_manual(values=diagnosis_col)+
  labs(x='PC1',y='% expanded repertoire clustered',title='')+
  theme_classic()+
  theme(
    legend.position = "none",
    plot.title = element_text(hjust = 0.5, size=12),
    axis.text.x = element_text(size=11),axis.title.x = element_text(size=13),
    axis.text.y = element_text(size=11),axis.title.y = element_text(size=11)
    )-> pl
pl
ggsave(plot=pl,filename = '../figures/4/D-right.pdf',width=2.5,height=2.5, dpi="retina")


```




## 4E

% clustered and GZMB+Tem
```{r fig.height=2.75, fig.width=2.75}

# % clus pheno
pseudo0=min(tcr_analysis$clus$pct$clustered)

tcr_analysis$clus$pheno %>% 
  filter(donor_id %in% clustered$donor_id) %>% 
  #GZMB+Tem
  mutate(pheno=replace(pheno,pheno %in% c('CD8.TemTerm','CD8.TEMRA','CD4.CTL'),'GZMB+Tem')) %>% 
  group_by(donor_id,pheno) %>% summarise(n=sum(n)) %>% ungroup() %>% 
  group_by(donor_id) %>% mutate(pct=n/sum(n)*100) %>% select(-n) %>% 
  pivot_wider(names_from='pheno',values_from='pct',values_fill=0) %>% 
  pivot_longer(!donor_id,names_to='pheno',values_to='pct') %>% 
  mutate(pct=pct+pseudo0) %>% 
  left_join(ords$Tcell$PCA %>% left_join(obs %>% select(sample_id,donor_id) %>% distinct())) %>% 
  left_join(donor_md %>% select(donor_id,cohort) %>% distinct()) %>% 
  distinct() %>% filter(!is.na(PC1)) %>%
  filter(pheno=='GZMB+Tem') %>% 

  ggplot(aes(PC1*-1, pct))+
  geom_point(aes(color=cohort))+
  geom_smooth(method='lm',size=1,alpha=0.2, color='grey20')+
  ggpubr::stat_cor(label.sep='\n',label.y = 90)+
  scale_color_manual(values=diagnosis_col)+scale_fill_manual(values=diagnosis_col)+
  labs(x='PC1',y='% CD8+Tem among\nclustered clones',title='GZMB+Tem')+
  theme_classic()+
  theme(
    legend.position = "none",
    plot.title = element_text(hjust = 0.5, size=12),
    axis.text.x = element_text(size=11),axis.title.x = element_text(size=13),
    axis.text.y = element_text(size=11),axis.title.y = element_text(size=13)
    )-> pl
pl
ggsave(plot=pl,filename = '../figures/4/E-left.pdf',width=2.75,height=2.75, dpi="retina")


```

MDE
```{r fig.height=3, fig.width=3}
as_tibble(obs) %>%
  select(clone_id,donor_id) %>% distinct() %>% 
  filter(donor_id=='Maura_2023.PT85', clone_id!='',!is.na(clone_id)) %>%
  filter(clone_id %in% tcr[tcr$clone_size>1,]$clone_id) %>% 
  left_join(tcr_analysis$clus$clon_clus) %>% drop_na() %>% 
  group_by(clus_id) %>% tally() %>% arrange(-n)
# 'Maura_2023.PT85-TRB-10'

clone_plot = tcr_analysis$clus$clon_clus %>% 
  filter(clus_id=='Maura_2023.PT85-TRB-10') %>% pull(clone_id)

obs %>% 
  mutate(is = clone_id %in% clone_plot) %>% 
  ggplot(aes(MDE1,MDE2))+
  #geom_point(data = . %>% filter(!is), size=0.01,color='grey75',alpha=0.1)+
  scattermore::geom_scattermore(color='grey80')+
  geom_point(data = . %>% filter(is), size=1, aes(color=clone_id))+
  scale_color_manual(values = long_col_vector[1:length(clone_plot)])+
  theme_void()+
  theme(legend.position = 'none') -> pl
pl
ggsave(plot=pl,filename = '../figures/4/E-right.png',width=2.5,height=2.5, dpi="retina")
```

GZMB MDE
```{r fig.height=3, fig.width=3}
gzmb = read.csv('../preprocessing/data/Tcell_exp.csv') %>% select(obs_names,GZMB)

obs %>% 
  left_join(gzmb) %>% 
  ggplot(aes(MDE1,MDE2,color=range01(GZMB)))+
  scattermore::geom_scattermore()+
  scale_color_distiller(palette = 'Reds',direction = 1)+
  theme_void()+
  theme(legend.position = 'none') -> pl
pl
ggsave(plot=pl,filename = '../figures/4/E-GZMB.png',width=2.5,height=2.5, dpi="retina")
```



## 4E - selected cluster motif

```{r}
x = read.csv('../preprocessing/data/tcr_clustering.csv') %>% filter(subject=='Maura_2023.PT85')
x %>% group_by(cdr3s) %>% tally() %>% arrange(-n) %>% head(1)
cdr3s.pl=c('CAVSANQAGTALIF', 'CAVSSNQAGTALIF', 'CAVSVNQAGTALIF', 'CAVSVNQAGTALIF', 'CAVSVNQAGTALIF')

read.csv('../preprocessing/data/tcr_clustering.csv') %>% 
  filter(subject=='Maura_2023.PT85', CDR3aa %in% cdr3s.pl)

tcr %>% filter(donor_id=='Maura_2023.PT85',CDR3aa %in% cdr3s.pl) %>% 
  select(chain,CDR3aa,v_gene,j_gene) %>% distinct() %>% arrange(chain) %>% 
  write.csv('~/tmp/CDR3s.csv',row.names=F)


```


## 4F

```{r fig.height=2, fig.width=2.5}
dat = tcr_analysis$nonviral$CD8.TemTerm %>% arrange(-logFC)

gene.pl = dat %>% arrange(-logFC) %>% head(10) %>% pull(gene)
#gene.pl = c(dat %>% arrange(-logFC) %>% head(10) %>% pull(gene),'GZMK','CD37')
#gene.pl = c('GNLY','FGFBP2','ITGB1','GZMB','ZNF683','LGALS1')

dat %>% arrange(-logFC) %>% 
  mutate(rank = row_number()) %>% 
  filter(rank < 100) %>% mutate(rank=rev(rank)) %>% 
  ggplot(aes(rank,logFC))+
  geom_point(size=1, aes(color=gene %in% gene.pl))+
  scale_color_manual(values=c(`TRUE`='dodgerblue',`FALSE`='grey80'))+
  scale_x_continuous(breaks = c(0,25,50,75,100),labels=c(100,75,50,25,1))+
  ggrepel::geom_text_repel(data = . %>% filter(gene %in% gene.pl),
    aes(label=gene), force=50, max.overlaps = 100)+
  labs(x='Rank', y='log fold-change\nnon-viral / viral')+
  theme(legend.position = 'none') -> pl
pl
ggsave(plot=pl,filename = '../figures/4/F.png',height=2,width=2.5,dpi="retina")
```


```{r fig.height=3, fig.width=3}

dat = tcr_analysis$nonviral$CD8.TemTerm %>% arrange(-logFC)
gene.pl = dat %>% arrange(-logFC) %>% head(10) %>% pull(gene)

dat %>% filter(p.value<0.05) %>% 
  mutate(FDR = ifelse(FDR<10e-10,10e-10,FDR)) %>% 
  ggplot(aes(logFC,-log10(FDR)))+
  geom_point(size=1, aes(color=gene %in% gene.pl))+
  scale_color_manual(values=c(`TRUE`='dodgerblue',`FALSE`='grey80'))+
  theme(legend.position = 'none') -> pl
pl
ggsave(plot=pl,filename = '../figures/4/F-2.png',height=3,width=3,dpi="retina")

dat %>% filter(p.value<0.05) %>% 
  mutate(FDR = ifelse(FDR<10e-10,10e-10,FDR)) %>% 
  ggplot(aes(logFC,-log10(FDR)))+
  geom_point(size=1, aes(color=gene %in% gene.pl))+
  scale_color_manual(values=c(`TRUE`='dodgerblue',`FALSE`='grey80'))+
  ggrepel::geom_text_repel(data = . %>% filter(gene %in% gene.pl),
    aes(label=gene), force=50, max.overlaps = 100)+
  theme(legend.position = 'none') -> pl
pl
ggsave(plot=pl,filename = '../figures/4/F-2.pdf',height=3,width=3,dpi="retina")


```


## 4G

```{r fig.height=3.75, fig.width=3}

dat = obs %>% select(obs_names,MDE1,MDE2,Nonviral)

dat %>% drop_na() %>% 
  sample_n(200000) %>% 
  ggplot(aes(MDE1,MDE2))+
  scattermore::geom_scattermore(aes(color=Nonviral))+
  scale_color_distiller(palette = 'Reds',direction = 1)+
  theme_void()+
  theme(legend.position = 'bottom',strip.text.x = element_text(size = 15))->pl
pl
ggsave(plot=pl,filename = '../figures/4/G.png',width=3.75,height=4, dpi="retina")



```

## 4H

plot key correlates
```{r fig.height=2.5, fig.width=2.25}
th = theme(legend.position = "none",
  plot.title = element_text(hjust = 0.5, size=12),
  axis.text.x = element_text(size=11),axis.title.x = element_text(size=12),
  axis.text.y = element_text(size=11),axis.title.y = element_text(size=11))

dat = obs %>% 
  filter(sample_id %in% ords$Tcell$PCA$sample_id) %>% 
  select(donor_id,Nonviral) %>% drop_na() %>% 
  group_by(donor_id) %>% summarise_all(.funs = mean) %>% 
  left_join(donor_md %>% select(donor_id,cohort) %>% distinct()) %>% 
  filter(cohort!='Non') %>% 
  mutate(cohort=factor(cohort,c('MGUS','SMM','MM')))

# PC1
dat %>% 
  left_join(ords$Tcell$PCA %>% 
    left_join(comp$Tcell %>% select(sample_id,donor_id) %>% distinct())) %>% 
  filter(!is.na(PC1)) %>% 
  ggplot(aes(PC1*-1,Nonviral))+geom_point(size=2, aes(color=cohort))+
  geom_smooth(method='lm',size=1,alpha=0.2, color='grey20')+
  ggpubr::stat_cor(label.sep='\n',label.x =-0.12 , label.y = 0.45)+
  scale_color_manual(values=diagnosis_col)+scale_fill_manual(values=diagnosis_col)+
  labs(x='PC1\n', y='Non-viral specificity signature',title='')+
  scale_y_continuous(breaks=c(0.1,0.2,0.3,0.4,0.5),limits=c(0.05,0.55))+
  theme_classic()+theme(legend.position = 'none')+th->pl
pl
ggsave(plot=pl, filename='../figures/4/H-1.pdf',width=2.5,height=2.75, dpi="retina")

# Clustered
psuedo0=0.1
dat %>% 
  left_join(tcr_analysis$clus$pct %>% select(donor_id,clustered)) %>% distinct() %>% 
  filter(!is.na(clustered)) %>% 
  ggplot(aes(log10(clustered+psuedo0),Nonviral))+geom_point(size=2, aes(color=cohort))+
  geom_smooth(method='lm',size=1,alpha=0.2, color='grey20')+
  ggpubr::stat_cor(label.sep='\n')+
  scale_color_manual(values=diagnosis_col)+scale_fill_manual(values=diagnosis_col)+
  scale_x_continuous(breaks=c(0,1,log10(50)), limits=c(0,log10(50)+0.1), labels=c(1,10,50))+
  annotation_logticks(sides='b',short=unit(0.1,'cm'),mid=unit(0.1,'cm'),long=unit(0.1,'cm'))+
  labs(x='% expanded repertoire clustered', y='Non-viral specificity signature',title='')+
  theme_classic()+theme(legend.position = 'none')+th->pl
pl
ggsave(plot=pl, filename='../figures/4/H-2.pdf',width=2.5,height=2.5, dpi="retina")

# Clonality
dat %>% 
  left_join(tcr_analysis$clonality %>% 
    filter(group=='all') %>% select(donor_id,clon)) %>% distinct() %>% 
  filter(!is.na(clon)) %>% 
  ggplot(aes(clon,Nonviral))+geom_point(size=2, aes(color=cohort))+
  geom_smooth(method='lm',size=1,alpha=0.2, color='grey20')+
  ggpubr::stat_cor(label.sep='\n')+
  scale_color_manual(values=diagnosis_col)+scale_fill_manual(values=diagnosis_col)+
  annotation_logticks(sides='b',short=unit(0.1,'cm'),mid=unit(0.1,'cm'),long=unit(0.1,'cm'))+
  labs(x='Clonality', y='Non-viral specificity signature',title='')+
  theme_classic()+theme(legend.position = 'none')+th->pl
pl
ggsave(plot=pl, filename='../figures/4/H-3.pdf',width=2.5,height=2.5, dpi="retina")


```


## 4I

```{r fig.width=1.6, fig.height=3}

dat = obs %>% 
  filter(sample_id %in% ords$Tcell$PCA$sample_id) %>% 
  select(donor_id,Nonviral) %>% drop_na() %>% 
  group_by(donor_id) %>% summarise_all(.funs = mean) %>% 
  left_join(donor_md %>% select(donor_id,cohort) %>% distinct()) %>% 
  filter(cohort!='Non') %>% 
  mutate(cohort=factor(cohort,c('MGUS','SMM','MM')))

dat %>% 
  ggplot(aes(cohort,Nonviral,fill=cohort))+
  geom_boxplot(outlier.alpha = 0)+
  geom_jitter(width=0.2,height=0,size=0.2)+
  ggpubr::stat_compare_means(
    comparisons = list(c('MGUS','MM'),c('SMM','MM')),
  method = 'wilcox.test',size=3.5)+
  scale_fill_manual(values=diagnosis_col)+
  labs(y='Non−viral specificity signature')+
  ylim(c(0.075,0.64))+
  theme_classic()+
  theme(
    legend.position = "none",
    plot.title = element_text(hjust = 0.5, size=12),
    axis.title.x = element_blank(), 
    axis.text.x = element_text(angle = 45, vjust = 1, hjust=1, size=11),
    axis.title.y = element_text(size=13), 
    axis.text.y = element_text(size=11)
  )-> pl
pl
ggsave(plot=pl, filename='../figures/4/I.pdf',width=1.6,height=3, dpi="retina")
```




## Friedrich 2023 TCE analysis

TCE-expanded TCRs, n=3
```{r fig.height=3, fig.width=9}

dat = read.csv('../resources/Friedrich_2023-longit.csv')

p0=min(c(dat$p1,dat$p2) %>% .[.>0])

dat %>% 
  filter(p1>0,p2>0) %>% 
  mutate(plt = ifelse(sig & (p2>p1),'TCE-expanded',' ')) %>%
  ggplot(aes((p1+p0)*100,(p2+p0)*100))+facet_grid(~pt)+
  geom_point(aes(color=plt))+
  scale_color_manual(values = c('TCE-expanded'='dodgerblue',' '='grey70'))+
  geom_abline(slope=1, intercept=0)+
  scale_x_log10(breaks=c(0.1,1,10),labels=c('0.1','1','10'),limits=c(0.025,40))+
  scale_y_log10(breaks=c(0.1,1,10),labels=c('0.1','1','10'),limits=c(0.025,40))+
  annotation_logticks(sides='lb')+
  labs(x='% pre-treatment',y='% post-treatment',color='TCE-expanded')+
  coord_fixed()+
  theme(
    panel.border = element_rect(color = "black", fill = NA, size = 0.5),
    axis.text.y = element_text(size=11),
    axis.text.x = element_text(angle = 45, vjust = 1, hjust=1,size=11),
    axis.title.y = element_text(size=12),
    axis.title.x = element_text(size=12)
  )


```

TCE-expanded TCRs, merged
```{r fig.height=3, fig.width=4}

dat = read.csv('../resources/Friedrich_2023-longit.csv')

p0=min(c(dat$p1,dat$p2) %>% .[.>0])

dat %>% 
  filter(p1>0,p2>0) %>% 
  mutate(plt = ifelse(sig & (p2>p1),'TCE-expanded',' ')) %>%
  ggplot(aes((p1+p0)*100,(p2+p0)*100))+#facet_grid(~pt)+
  geom_point(aes(color=plt))+
  scale_color_manual(values = c('TCE-expanded'='dodgerblue',' '='grey70'))+
  geom_abline(slope=1, intercept=0)+
  scale_x_log10(breaks=c(0.1,1,10),labels=c('0.1','1','10'),limits=c(0.025,40))+
  scale_y_log10(breaks=c(0.1,1,10),labels=c('0.1','1','10'),limits=c(0.025,40))+
  annotation_logticks(sides='lb')+
  labs(x='% pre-treatment',y='% post-treatment',color='TCE-expanded')+
  coord_fixed()+
  theme(
    panel.border = element_rect(color = "black", fill = NA, size = 0.5),
    axis.text.y = element_text(size=11),
    axis.text.x = element_text(angle = 45, vjust = 1, hjust=1,size=11),
    axis.title.y = element_text(size=12),
    axis.title.x = element_text(size=12)
  )->pl
ggsave(plot=pl,filename = '../figures/4/Friedrich23-longitMerged.pdf',
       height=3,width=4, dpi="retina")


```


TCE-expanded boxplot, n=3
```{r fig.height=3, fig.width=4}
#(match style of non-viral boxplot)

dat = read.csv('../resources/Friedrich_2023-nonviral.csv')

dat
dat %>%
  ggplot(aes(exp,nonvir10_UCell))+facet_grid(~pt)+
  geom_violin()+geom_boxplot(alpha = 0)+
  ggpubr::stat_compare_means(method = 'wilcox')

dat %>% 
  mutate(plt = ifelse(exp,'TCE-expanded',' ')) %>%
  ggplot(aes(exp,nonvir10_UCell))+facet_grid(~pt)+
  geom_violin(aes(fill=plt))+geom_boxplot(alpha = 0)+
  scale_fill_manual(values = c('TCE-expanded'='dodgerblue',' '='grey70'))+
  ggpubr::stat_compare_means(comparisons = list(c('FALSE','TRUE')),
  method = 'wilcox.test',size=3.5)+
  ylim(c(0,0.9))+
  labs(y='Non-viral score')+
  theme(
    axis.title.x=element_blank(),axis.text.x=element_blank(),axis.ticks.x=element_blank(),
    axis.text.y = element_text(size=11),
    axis.title.y = element_text(size=12),
  )

lmerTest::lmer(nonvir10_UCell ~ exp + (1|pt), dat) %>% summary()

```

TCE-expanded boxplot, merged
```{r fig.height=3, fig.width=3.15}
#(match style of non-viral boxplot)

dat = read.csv('../resources/Friedrich_2023-nonviral.csv')

dat %>% 
  mutate(plt = ifelse(exp,'TCE-expanded',' ')) %>%
  group_by(pt,raw_clonotype_id,exp,plt) %>% summarise(nonvir10_UCell=median(nonvir10_UCell)) %>% 
  ggplot(aes(exp,nonvir10_UCell))+#facet_grid(~pt)+
  geom_violin(aes(fill=plt))+
  geom_boxplot(aes(fill=plt),outliers=F)+
  geom_jitter(data=. %>% filter(exp),width=0.2,height=0,size=1)+
  
  scale_fill_manual(values = c('TCE-expanded'='dodgerblue',' '='grey80'))+
  ggpubr::stat_compare_means(comparisons = list(c('FALSE','TRUE')),
  method = 'wilcox.test',size=3.5)+
  ylim(c(0,0.9))+
  labs(y='Non-viral signature per-clone')+
  theme(
    axis.title.x=element_blank(),axis.text.x=element_blank(),axis.ticks.x=element_blank(),
    axis.text.y = element_text(size=11),
    axis.title.y = element_text(size=12),
  )->pl
pl
ggsave(plot=pl,filename = '../figures/4/Friedrich23-percloneMerged.pdf',
       height=3,width=3.15, dpi="retina")


```




## 









































































