---
title: "5"
output:
  html_document:
    code_folding: hide
    toc: true # table of content true
    toc_depth: 3  # upto three depths of headings (specified by #, ## and ###)
    number_sections: false  ## if you want number sections at each table header
params:
    args: myarg
---

## Setup

```{r eval=T, hide=T}

library(tidyverse)
library(ggpubr)
library(RColorBrewer)
library(viridis)
source('../resources/aes.R')
range01 <- function(x){(x-min(x))/(max(x)-min(x))}
load(file = '../preprocessing/data/comp.RData')
load(file = '../preprocessing/data/ords.RData')
load(file = '../preprocessing/data/tcr_analysis.RData')
obs = read.csv('../preprocessing/data/Tcell_obs.csv')
tcr = read.csv('../preprocessing/data/import/Tcell-scTCR.csv')
donor_md = read.csv('../preprocessing/data/import/metadata-donor.csv')
sort_id = read.csv('../resources/Foster_2024_sort_id.csv')
tumour_modules_pct = read.csv('../preprocessing/data/tumour_modules_pct.csv')
dir.create('../figures/5')

```

## 5A

```{r fig.height=3, fig.width=5.5, eval=T, hide=T}

dat.pl = read_csv('../preprocessing/data/tcell_tum_association_results.csv')

i.order=c('Paraprotein','B2m','Aspirate % CD138+','% tumour expressing\nstress pathway')
j.order=c('T cell skewing','Exaggerated T cell aging','CD8.TEMRA\n(normalised % T cells)','Repertoire clonality',"Teff.IFIT2\n(normalised % T cells)" ,'Effector signature\n(CD69, TNF, IFNG)','Non-viral specificity\nscore')

dat.pl %>% 
  mutate(j.pl=factor(j.pl,j.order)) %>% mutate(i.pl=factor(i.pl,rev(i.order))) %>% 
  ggplot(aes(j.pl,i.pl))+
  geom_tile(aes(fill=r), color='black', size=0.25)+
  geom_text(data = . %>% filter(sig_gr!=''), 
            aes(label=sig_gr),position = position_nudge(x = -0, y= -0.1), size=5.5)+
  labs(fill='Correlation  ')+
  scale_fill_gradient2(
    low='dodgerblue',mid='white',high='#eb676e', na.value = 'grey50',
    breaks=c(-0.25,0,0.25,0.75), labels=c('-0.25','0','0.25','0.75')
  )+
  theme_void()+
  theme(
    legend.position = 'bottom',legend.ticks = element_blank(),
    legend.key.height = unit(0.2, "cm"),
    legend.key.width = unit(0.5, "cm"), legend.title = element_text(size=9),
    axis.text.y = element_text(size=11, hjust = 1),
    axis.text.x = element_text(angle = 45, vjust = 1, hjust=1, size=10)
  )-> pl
pl
ggsave(plot=pl,filename = '../figures/5/A.pdf',width=5.5,height=3, dpi="retina")
```





## 5B

Maura et al. Paraprotein data missing (inquire to authors)
```{r fig.height=2.5, fig.width=2.5}
th = theme(legend.position = "none",
  plot.title = element_text(hjust = 0.5, size=12),
  axis.text.x = element_text(size=11),axis.title.x = element_text(size=13),
  axis.text.y = element_text(size=11),axis.title.y = element_text(size=13))

IgG_and_IgA_isotype_tumours = read.csv('../resources/IgG_and_IgA_isotype_tumours.csv')$donor_id

Paraprotein_plot = donor_md %>% select(donor_id,Paraprotein) %>% drop_na() %>% 
  filter(donor_id %in% IgG_and_IgA_isotype_tumours) %>% 
  rbind(
    read_csv('../integration/data/validation-metadata.csv') %>% 
      mutate(donor_id=donor,Paraprotein=PP_g.dL*10) %>% select(donor_id,Paraprotein) %>% drop_na()
  )

dat = ords$Tcell$PCA[,1:2] %>% 
  left_join(comp$Tcell %>% select(sample_id,donor_id,cohort) %>% distinct()) %>% 
  select(-sample_id) %>% mutate(source='Full') %>% 
  rbind(
    ords$valid[,1:2] %>% 
        left_join(
            read_csv('../integration/data/validation-metadata.csv')[,c('sample_id','diagnosis')]
        ) %>%
        dplyr::rename(donor_id='sample_id', cohort='diagnosis') %>% mutate(source='Botta et al.')
  ) %>% 
  group_by(source) %>% mutate(PC1=scale(PC1)) %>% 
  left_join(Paraprotein_plot) %>% filter(!is.na(Paraprotein))
  
dat %>% 
  ggplot(aes(Paraprotein,PC1))+
  geom_point(size=2, aes(color=cohort))+
  geom_smooth(method='lm',size=1,alpha=0.2, color='grey20')+
  ggpubr::stat_cor(label.sep='\n', label.x=38)+
  scale_color_manual(values=diagnosis_col)+scale_fill_manual(values=diagnosis_col)+
  labs(x='Paraprotein',y='T cell skewing',title='')+
  theme_classic()+theme(legend.position = 'none')+th-> pl
pl
ggsave(plot=pl,filename = '../figures/5/B-left.pdf',width=2.5,height=2.5, dpi="retina")
```


```{r fig.height=2.5, fig.width=2.25}

comp$Tcell %>% filter(
  !donor_id %in% c(donors.longit,donor.Tex_hi),tissue=='BM',sampleSize>100) %>% 
  # Remove Foster_2024 samples with T cell depletion/CD8-enrichment
  filter( ! sample_id %in% sort_id[sort_id$sort_id!='T cell-enriched',]$sample_id ) %>% 
  filter(celltype=='Teff') %>% filter(study_id!='Zavidij_2020') %>%
  
  ggplot(aes(aspirate_CD138pos,prop*100))+
  geom_point(size=2, aes(color=cohort))+
  geom_smooth(method='lm',size=1,alpha=0.2, color='grey20')+
  ggpubr::stat_cor(label.sep='\n')+
  scale_color_manual(values=diagnosis_col)+scale_fill_manual(values=diagnosis_col)+
  labs(x='Aspirate % CD138+',y=paste0('% T cells'),title='Teff')+
  scale_y_log10()+annotation_logticks(sides='l')+
  theme_classic()+
  theme(
    legend.position = "none",
    plot.title = element_text(hjust = 0.5, size=12),
    axis.text.x = element_text(size=11),axis.title.x = element_text(size=12),
    axis.text.y = element_text(size=11),axis.title.y = element_text(size=12)
    )-> pl
pl 
ggsave(plot=pl,filename = '../figures/5/B-right.pdf',width=2.5,height=2.5, dpi="retina")


comp$Tcell %>% filter(
  !donor_id %in% c(donors.longit,donor.Tex_hi),tissue=='BM',sampleSize>100) %>% 
  # Remove Foster_2024 samples with T cell depletion/CD8-enrichment
  filter( ! sample_id %in% sort_id[sort_id$sort_id!='T cell-enriched',]$sample_id ) %>% 
  filter(celltype=='Teff') %>% 
  left_join(tumour_modules_pct) %>% filter(!is.na(pathway)) %>% 
  filter(pathway_neat=='Stress') %>% 
  ggplot(aes(pct,prop*100))+
  geom_point(size=2, aes(color=cohort))+
  geom_smooth(method='lm',size=1,alpha=0.2, color='grey20')+
  ggpubr::stat_cor(label.sep='\n')+
  scale_color_manual(values=diagnosis_col)+scale_fill_manual(values=diagnosis_col)+
  labs(x='pct stress',y=paste0('% T cells'),title='Teff')+
  scale_y_log10()+annotation_logticks(sides='l')+
  theme_classic()+
  theme(
    legend.position = "none",
    plot.title = element_text(hjust = 0.5, size=12),
    axis.text.x = element_text(size=11),axis.title.x = element_text(size=12),
    axis.text.y = element_text(size=11),axis.title.y = element_text(size=12)
    )-> pl
pl 
ggsave(plot=pl,filename = '../figures/5/B-right_str.pdf',width=2.5,height=2.5, dpi="retina")


comp$Tcell %>% filter(
  !donor_id %in% c(donors.longit,donor.Tex_hi),tissue=='BM',sampleSize>100) %>% 
  # Remove Foster_2024 samples with T cell depletion/CD8-enrichment
  filter( ! sample_id %in% sort_id[sort_id$sort_id!='T cell-enriched',]$sample_id ) %>% 
  filter(celltype=='Teff') %>% 
  left_join(tumour_modules_pct) %>% filter(!is.na(pathway)) %>% 
  filter(pathway_neat=='TNFa') %>% 
  ggplot(aes(pct,prop*100))+
  geom_point(size=2, aes(color=cohort))+
  geom_smooth(method='lm',size=1,alpha=0.2, color='grey20')+
  ggpubr::stat_cor(label.sep='\n')+
  scale_color_manual(values=diagnosis_col)+scale_fill_manual(values=diagnosis_col)+
  labs(x='pct TNFa',y=paste0('% T cells'),title='Teff')+
  scale_y_log10()+annotation_logticks(sides='l')+
  theme_classic()+
  theme(
    legend.position = "none",
    plot.title = element_text(hjust = 0.5, size=12),
    axis.text.x = element_text(size=11),axis.title.x = element_text(size=12),
    axis.text.y = element_text(size=11),axis.title.y = element_text(size=12)
    )-> pl
pl 
```


## 5C

```{r fig.height=2.5, fig.width=2.25}

dat = read.csv('../resources/TEMRA_score.csv') %>% 
  left_join(obs %>% select(obs_names,sample_id,pheno)) %>% 
  filter(pheno=='Teff.IFIT2') %>% 
  group_by(sample_id) %>% summarise(score=median(score)) %>% 
  left_join(comp$Tcell %>% select(sample_id,donor_id,tissue,sampleSize,cohort) %>% distinct()) %>% 
  filter( ! donor_id %in% c(donors.longit,donor.Tex_hi),tissue=='BM',sampleSize>100) %>% 
  filter( ! sample_id %in% sort_id[sort_id$sort_id!='T cell-enriched',]$sample_id ) %>% 
  left_join(tumour_modules_pct) %>% drop_na()

dat %>% filter(pathway_neat=='Stress') %>% 
  ggplot(aes(pct,score))+
  geom_point(size=2, aes(color=cohort))+
  geom_smooth(method='lm',size=1, alpha=0.2, color='grey20')+
  ggpubr::stat_cor(label.sep='\n',label.x = 5, label.y= 0.45)+
  scale_color_manual(values=diagnosis_col)+scale_fill_manual(values=diagnosis_col)+
  labs(x='% tumour expressing\nstress pathway',y='CD8.TEMRA score',title='Teff.IFIT2')+
  scale_y_continuous(breaks=c(0.1,0.2,0.3,0.4,0.5), limits=c(0,0.55))+
  theme_classic()+
  theme(
    legend.position = "none",
    plot.title = element_text(hjust = 0.5, size=12),
    axis.text.x = element_text(size=11),axis.title.x = element_text(size=11),
    axis.text.y = element_text(size=11),axis.title.y = element_text(size=11)
    )-> pl
pl
ggsave(plot=pl,filename = '../figures/5/C-1.pdf',width=2.25,height=2.5, dpi="retina")

```

```{r fig.height=2.75, fig.width=2.25}

# Clone subsets
clones.expanded = names(table(obs$clone_id[obs$clone_id!='']) %>% .[.>1])
clones.Teff_IFIT2 = obs[obs$pheno=='Teff.IFIT2',]$clone_id
clones.Tem_GZMB = obs %>% 
  filter(clone_id %in% tcr[tcr$type=='CD8',]$clone_id) %>% 
  mutate(Tem_GZMB = pheno %in% c('CD8.TemTerm','CD8.TEMRA','CD4.CTL')) %>% 
  group_by(clone_id,Tem_GZMB) %>% tally() %>% ungroup() %>% 
  group_by(clone_id) %>% mutate(p=n/sum(n)) %>% 
  filter(Tem_GZMB,p>0.5)

# Data prep
dat = read.csv('../resources/TEMRA_score.csv') %>% 
  left_join(obs %>% select(obs_names,sample_id,pheno,clone_id)) %>% filter(clone_id!='') %>% 
  
  filter(pheno=='Teff.IFIT2') %>% 
  
  left_join(comp$Tcell %>% select(sample_id,donor_id,tissue,sampleSize,cohort) %>% distinct()) %>% 
  filter( ! donor_id %in% c(donors.longit,donor.Tex_hi),tissue=='BM',sampleSize>100) %>% 
  filter( ! sample_id %in% sort_id[sort_id$sort_id!='T cell-enriched',]$sample_id ) %>% 
  
  filter(clone_id %in% c(clones.expanded,clones.Teff_IFIT2)) %>% 
  group_by(clone_id) %>% summarise(score=median(score)) %>% 
  mutate(Tem_GZMB = ifelse(
    clone_id %in% clones.Tem_GZMB$clone_id,'GZMB+Tem\nshared','GZMB+Tem\nunshared')) %>% 
  mutate(Tem_GZMB = factor(Tem_GZMB,c('GZMB+Tem\nunshared','GZMB+Tem\nshared')))


# Plot
dat %>% 
  ggplot(aes(Tem_GZMB,score))+
  geom_boxplot(aes(fill=Tem_GZMB),outliers = F)+
  scale_fill_manual(values = c(
    'GZMB+Tem\nshared'=Tcell_pheno_colors[['CD8.TemTerm']], 'GZMB+Tem\nunshared'='grey70'))+
  geom_jitter(width=0.2,height=0,size=0.1)+
  ggpubr::stat_compare_means(comparisons = list(c('GZMB+Tem\nshared','GZMB+Tem\nunshared')), size=3)+
  #ylim(c(0,0.65))+
  labs(y='Clone median\nCD8.TEMRA score',title='Expanded Teff.IFIT2\nclone overlap')+
  theme(
    legend.position = 'none',
    plot.title = element_text(hjust = 0.5, size=11),
    axis.title.x=element_blank(),
    axis.text.x = element_text(angle = 45, vjust = 1, hjust=1, size=11),
    plot.margin = margin(t = 0, r = 20, b = 0, l = 20, unit = "pt")
  )-> pl
pl
ggsave(plot=pl,filename = '../figures/5/C-2.pdf',width=2.25,height=2.75, dpi="retina")
```




## 5D

```{r fig.width=5, fig.height=3}

# Subset of donors
dat = obs %>% filter(donor_id %in% paste0('Foster_2024.',c('MM1','MM2','MM5'))) %>% 
  mutate(donor_id=str_remove(donor_id,'Foster_2024.'))

# Largest Teff.IFIT2 clones
clones.Teff_IFIT2_top = dat %>% 
  filter(pheno=='Teff.IFIT2',clone_id!='') %>% 
  group_by(donor_id,clone_id) %>% tally() %>% arrange(-n) %>% ungroup() %>% 
  group_by(donor_id) %>% slice_head(n = 15)

# Phenotype of these clones
pheno_plot = c(unique(obs[obs$subset=='CD8',]$pheno),'Teff.IFIT2','Prolif.','ISG.ISG15')
dat = dat %>% 
  filter(clone_id %in% clones.Teff_IFIT2_top$clone_id) %>% 
  filter(pheno %in% pheno_plot) %>% 
  mutate(pheno = ifelse(pheno %in% c('CD8.TemTerm','CD8.TEMRA','CD4.CTL'),'GZMB+Tem',pheno)) %>% 
  group_by(donor_id,clone_id,pheno) %>% tally() %>% arrange(-n) %>% ungroup() 

clone_id.pl = dat %>% group_by(clone_id) %>% summarise(n=sum(n)) %>% arrange(n) %>% pull(clone_id)
pheno.order.pl = c('Teff.IFIT2','GZMB+Tem',"CD8.Tn","CD8.Tcm","CD8.Trm","CD8.Tem.KLRG1","CD8.Tem.IL7R","CD8.TemActive","ISG.ISG15","Prolif.")

dat %>% 
  mutate(clone_id=factor(clone_id,clone_id.pl)) %>% 
  mutate(pheno=factor(pheno,rev(pheno.order.pl))) %>% 
  
  
  ggplot(aes(clone_id,n,fill=pheno))+
  facet_grid(.~donor_id,space='free',scales='free')+
  geom_col(color='black')+
  scale_y_continuous(expand = c(0, 0), limits=c(0,160))+
  scale_x_discrete(expand = c(0.15, 0.15))+
  guides(fill=guide_legend(ncol=1))+
  scale_fill_manual(values = c(Tcell_pheno_colors,'GZMB+Tem'='#377EB8'))+
  labs(x='Top expanded Teff.IFIT2 clones',y='N cells',fill='Phenotype')+
  theme(
    axis.text.x = element_blank(), axis.ticks.x = element_blank(),
    legend.position='right',legend.key.size = unit(0.3, "cm"),
    legend.text=element_text(),legend.title=element_blank(),
    strip.text.x = element_text(size=11), strip.background = element_blank(),
    panel.spacing = unit(0, "lines")
  )-> pl
pl
ggsave(plot=pl,filename = '../figures/5/D.pdf',width=5,height=2.5, dpi="retina")

```

## 5 - Control vs PCD split by BM PC % <10 & >10%

```{r fig.width=1.75, fig.height=3} 

p0 = min(comp$Tcell$prop[comp$Tcell$prop>0])*100

dat.pl = comp$Tcell %>% filter(
  !donor_id %in% c(donors.longit,donor.Tex_hi),tissue=='BM',sampleSize>100) %>% 
  # Remove Foster_2024 samples with T cell depletion/CD8-enrichment
  filter( ! sample_id %in% sort_id[sort_id$sort_id!='T cell-enriched',]$sample_id ) %>% 
  filter(celltype=='Teff')

dat.pl$is = (dat.pl$cohort=='Non') | (dat.pl$cohort!='Non' & dat.pl$study_id!='Zavidij_2020' & !is.na(dat.pl$aspirate_CD138pos))

dat.pl %>% filter(is) %>% 
  mutate(BM_PC_hi = ifelse(aspirate_CD138pos > 10,'hi','lo')) %>% 
  mutate(BM_PC_hi = ifelse(is.na(BM_PC_hi),'Non',BM_PC_hi)) %>% 
  
  
  ggplot(aes(x = BM_PC_hi, y = (prop*100)+p0, fill=BM_PC_hi))+
  geom_boxplot(outlier.alpha = 0)+
  geom_jitter(width=0.2,height=0,size=0.2)+
  ggpubr::stat_compare_means(comparisons = list(c('Non','hi'),c('Non','lo')),method = 'wilcox.test',size=3.5)+
  #scale_fill_manual(values=c(diagnosis_col,c('Pt'=diagnosis_col[['MM']])))+
  scale_y_log10()+annotation_logticks(sides='l')+
  labs(y='% T cells',title='Teff')+

  theme_classic()+
  theme(
    legend.position = "none",
    plot.title = element_text(hjust = 0.5, size=12),
    axis.title.x = element_blank(), 
    axis.text.x = element_text(angle = 45, vjust = 1, hjust=1, size=11),
    axis.title.y = element_text(size=13), 
    axis.text.y = element_text(size=11)
  )->pl
pl
###ggsave(plot=pl,filename = '../figures/5/__.pdf',width=1.25,height=3, dpi="retina")


```


## 5 - Teff overlap extended quantification

Chi2 and dotplot

```{r fig.height=2.5, fig.width=4.25}

# Quant
query='Teff.IFIT2'
dat = obs %>% filter(has_tcr=='True',pheno!=query,subset=='CD8')
dat$query_share = dat$clone_id %in% obs[obs$pheno==query,]$clone_id

out=list()
for (i in unique(dat$pheno)){
dat$i = dat$pheno==i
res = chisq.test(table(dat$i, dat$query_share))
out[[i]] = data.frame(p=res$p.value,Roe=(res$observed / res$expected)[2,2])
}
res = as_tibble(bind_rows(out,.id='pheno')) %>% 
  mutate(fdr=p.adjust(p,'BH'),sig=fdr<0.1) %>% arrange(p) 

# Plot
res$fdr[res$fdr==0] = min(res$fdr %>% .[.!=0])
res %>% left_join(labels2) %>% mutate(pheno=labels2) %>% 
  arrange(Roe) %>% mutate(pheno=factor(pheno,pheno)) %>% 
  ggplot(aes(pheno,'Teff share'))+
  geom_point(data = . %>% filter(sig),aes(fill=log2(Roe), size=-log10(fdr)), shape=21)+
  scale_fill_gradient2(low='dodgerblue',mid='white',high='red')+
  theme_bw()+
  theme(
    legend.position = 'bottom',
    axis.text.x = element_text(angle = 45, vjust = 1, hjust=1, size=9)
  )-> pl
pl
ggsave(plot=pl,filename = '../figures/5/overlap.pdf',width=4.25,height=2.5, dpi="retina")
  
print(res %>% left_join(labels2) %>% mutate(pheno=labels2) )
```

Alluvial
```{r fig.height=3, fig.width=2}
library(ggalluvial)

dat.pl = dat %>% group_by(pheno,query_share) %>% tally() %>% 
  group_by(query_share) %>% mutate(pct=n/sum(n)*100) %>% ungroup() %>% 
  mutate(share=ifelse(query_share,'Teff','Other')) %>% 
  left_join(labels2) %>% mutate(pheno=labels2) %>% 
  select(pheno,share,pct) 

pheno.order = arrange(dat.pl[dat.pl$share=='Teff',],-pct)$pheno

dat.pl %>% 
  mutate(pheno=factor(pheno,pheno.order)) %>% 

  ggplot(aes(x=share, y=pct, stratum = pheno, alluvium = pheno ,fill = pheno)) +
  stat_alluvium(geom="flow",color='black', alpha=1, position=position_dodge(width=0))+
  stat_stratum(width = .1)+
  geom_text(stat = "stratum", aes(label = after_stat(stratum)))+
  scale_fill_manual(values = Tcell_pheno_colors)+
  theme(legend.position = 'none')->pl
pl
ggsave(plot=pl,filename = '../figures/5/alluvial.pdf',width=2,height=3, dpi="retina")



```





## 5E *

```{r fig.height=2.5, fig.width=2.5}

dat = read_csv('../resources/neoantigen_predictions.csv') %>% 
  arrange(-score) %>% group_by(epitope) %>% slice_head(n=1) %>% ungroup() %>% 
  filter(score>0.7)

dat.pl = obs %>% filter(donor_id %in% dat$donor_id) %>% 
  left_join(
    tcr[tcr$chain=='TRB',] %>% select(clone_id,CDR3aa) %>% distinct()
  ) %>% 
  left_join(dat %>% select(donor_id,CDR3aa_beta,score), 
    by=c('donor_id'='donor_id','CDR3aa'='CDR3aa_beta')) %>% 
  mutate(is = !is.na(score))

colors = long_col_vector[1:length(unique(dat.pl[dat.pl$is,]$CDR3aa))]

dat.pl %>% ggplot(aes(MDE1,MDE2))+
  geom_point(data = . %>% filter(!is), size=0.1,color='grey75')+
  geom_point(data = . %>% filter(is), size=2.5, aes(fill=CDR3aa), shape=21)+
  scale_fill_manual(values = colors)+
  theme_void()+theme(legend.position = 'none')->pl
pl
ggsave(plot=pl,filename = '../figures/5/E-1.png',height=2.5,width=2.5,dpi="retina")


```


```{r fig.height=2.5, fig.width=1.5}
dat = read_csv('../resources/neoantigen_predictions.csv') %>% 
  arrange(-score) %>% group_by(epitope) %>% slice_head(n=1) %>% ungroup() %>% 
  filter(score>0.7)

dat.pl = obs %>% filter(donor_id %in% dat$donor_id) %>% 
  left_join(
    tcr[tcr$chain=='TRB',] %>% select(clone_id,CDR3aa) %>% distinct()
  ) %>% 
  left_join(dat %>% select(donor_id,CDR3aa_beta,score), 
    by=c('donor_id'='donor_id','CDR3aa'='CDR3aa_beta')) %>% 
  mutate(is = as.character(!is.na(score))) %>% 
  # Expanded
  filter(clone_id %in% (table(obs$clone_id[obs$clone_id!='']) %>% .[.>1] %>% names())) 

colors = c('FALSE'='grey80','TRUE'=Tcell_pheno_colors[['CD8.TemTerm']])

dat.pl %>% 
  group_by(is,clone_id) %>% summarise(Nonviral=mean(Nonviral)) %>% 
  ggplot(aes(is, Nonviral))+
  geom_boxplot(aes(fill=is), outliers = F)+
  scale_fill_manual(values = colors)+
  geom_jitter(eight=0,width=0.2, size=0.5)+
    ggpubr::stat_compare_means(label.x = 1.1, label.y=0.65,
      aes(label = paste0("P = ", after_stat(p.format))))+
  #ylim(c(0.1,0.675))+
  labs(y='Non-viral specificity signature')+
  theme(legend.position = 'none',
    axis.text.y=element_text(size=10),axis.title.y=element_text(size=11),
    axis.text.x=element_blank(), axis.title.x=element_blank(), axis.ticks.x=element_blank()
  )->pl
pl
ggsave(plot=pl,filename = '../figures/5/E-2.pdf',height=2.5,width=1.5,dpi="retina")

```



## 5F

Data prep
```{r fig.height=6, fig,width=7, eval=T, hide=T}
library(ComplexHeatmap)
tumour_DE = read.csv('../preprocessing/data/tumour_DE.csv',row.names=1)
load(file='../preprocessing/data/tumour_DE_fgsea.RData')

fgseas.select = fgseas[fgseas$pathway=='KEGG_ANTIGEN_PROCESSING_AND_PRESENTATION',] 
donor.sigAPP = fgseas.select[(fgseas.select$pval<0.05)&(fgseas.select$NES>0),]$donor_id

# Selected genes
KEGG_APC.g = c('HLA-A','HLA-B','HLA-C', 'B2M','HLA-DRA','HLA-DPA1','CD74','HLA-E','HLA-F','TAP1','TAP2','TAPBP','PSME1','PSME2')

donor.order = tumour_DE %>% filter(gene %in% KEGG_APC.g) %>% group_by(donor_id) %>%
  summarise(logFC=mean(logFC)) %>% arrange(logFC) %>% pull(donor_id)

dat.in = tumour_DE %>% filter(gene %in% KEGG_APC.g) %>%
    mutate(is = donor_id %in% donor.sigAPP) %>%
    mutate(donor_id = factor(donor_id,donor.order)) %>%
    group_by(gene) %>% mutate(logFC=as.vector(scale(logFC)))

dat.mat = dat.in %>% select(donor_id,gene,logFC) %>%
  mutate(donor_id=factor(donor_id,donor.order)) %>% 
  pivot_wider(names_from='donor_id',values_from='logFC',values_fill=NA) %>% 
  relocate(any_of(c('gene',donor.order))) %>% 
  mutate(gene=factor(gene,KEGG_APC.g)) %>% arrange(gene) %>% 
  data.frame() %>% column_to_rownames('gene') %>% as.matrix()

logFC.max=round(max(dat.in$logFC),2)
logFC.min=round(min(dat.in$logFC),2)
col_fun = circlize::colorRamp2(c(logFC.min, 0, logFC.max), c("dodgerblue", "white", "red"))

column_donor_md = dat.in %>% ungroup() %>% select(donor_id) %>% distinct() %>% 
  mutate(is_de = donor_id %in% donor.sigAPP) %>%
  left_join(
    read.csv('../preprocessing/data/import/metadata-donor.csv') %>% 
      select(donor_id,cohort) %>% distinct()
  ) %>% 
  mutate(donor_id=factor(donor_id,donor.order)) %>% arrange(donor_id) 

```

Plotting/saving
```{r fig.height=3, fig.width=4}

column_ha = columnAnnotation(
  " " = column_donor_md$cohort,
  col = list(` `=diagnosis_col),
  height = unit(4, "cm"),
  gp = gpar(col = "black"), gap = unit(0, "points"),
  annotation_name_side = "right", show_legend=F
)

row_ha = rowAnnotation(gene = anno_mark(at = 1:length(rownames(dat.mat)), labels = rownames(dat.mat)))

Heatmap(
  dat.mat,
  color=col_fun,
  na_col = 'grey80',
  top_annotation = column_ha,
  show_heatmap_legend=F,
  cluster_rows = F, cluster_columns = F,
  show_row_names = F, show_column_names = F, 
  right_annotation = row_ha, 
  row_names_gp = gpar(fontface='italic'),
  column_split = column_donor_md$is_de, border = TRUE, 
  column_title = c('MHC low', 'MHC high'),
  width = unit(6, "cm"), height = unit(4, "cm")
  ) -> hm

lgd_list = list(
  Legend(col_fun = col_fun, title = "Scaled log fold-change\ntumour / normal", at = c(logFC.min, 0, logFC.max), 
    direction = "horizontal",title_position = "topcenter",
    labels = c('Min', '', 'Max'),
    title_gp=gpar(fontface='plain')
  ))

draw(hm, annotation_legend_list = lgd_list, annotation_legend_side = "bottom")

grDevices::pdf("../figures/5/F.pdf", width = 4, height = 3)
draw(hm, annotation_legend_list = lgd_list, annotation_legend_side = "bottom")
grDevices::dev.off()

```


## 5G

```{r fig.height=3, fig.width=1.5}

tumour_DE = read.csv('../preprocessing/data/tumour_DE.csv',row.names=1)
load(file='../preprocessing/data/tumour_DE_fgsea.RData')
fgseas.select = fgseas[fgseas$pathway=='KEGG_ANTIGEN_PROCESSING_AND_PRESENTATION',] 

donor.all = unique(fgseas$donor_id)
donor.sigAPP = fgseas.select[(fgseas.select$pval<0.05)&(fgseas.select$NES>0),]$donor_id

dat = obs %>% filter(
  !donor_id %in% c(donors.longit,donor.Tex_hi),tissue=='BM') %>% 
  filter( ! sample_id %in% sort_id[sort_id$sort_id!='T cell-enriched',]$sample_id ) %>% 
  filter(donor_id %in% donor.all) %>% 
  select(donor_id,Nonviral) %>% drop_na() %>% 
  group_by(donor_id) %>% summarise(Nonviral=mean(Nonviral)) %>% 
  mutate(is = ifelse(donor_id %in% donor.sigAPP,'MHC high','MHC low')) %>% 
  left_join(donor_md %>% select(donor_id,cohort))
  
dat %>% 
  mutate(is=factor(is,c('MHC low','MHC high'))) %>% 
  ggplot(aes(is,Nonviral))+
  geom_boxplot(outlier.alpha = 0)+
  geom_jitter(aes(fill=cohort), width=0.2,height=0,size=2, shape=21)+
  scale_fill_manual(values=diagnosis_col)+
  stat_compare_means(method='wilcox',label.y=0.255,label.x=1.1,
    aes(label = paste0('P = ',after_stat(p.format))))+
  scale_y_continuous(breaks=c(.15,.2,.25),limit=c(.12,0.26))+
  labs(y='Non-viral specificity signature')+
  theme(
    legend.position = "none",
    axis.title.x = element_blank(), 
    axis.text.x = element_text(angle = 45, vjust = 1, hjust=1, size=11),
  )->pl
pl
ggsave(plot=pl,filename = '../figures/5/G.pdf',width=1.5,height=3, dpi="retina")

```


## ASCT-expanded clones baseline phenotype

Prep
```{r}

#CAR162_BSL=Foster_2024.MM1
#CAR197_BSL=Foster_2024.MM2
pois = read.csv('~/OneDrive/CARD-TCR/R/data/bulkTCR/poissonTesting.csv') %>% 
  filter(dc %in% c('CAR162_b','CAR197_b'), sig, p2>p1) %>% 
  select(dc,aa,v_call,j_call)
pois$dc=ifelse(pois$dc=='CAR162_b','Foster_2024.MM1','Foster_2024.MM2')
colnames(pois)=c('donor_id','CDR3aa','v_gene','j_gene')

dat = obs %>% filter(donor_id %in% c('Foster_2024.MM1','Foster_2024.MM2'), 
                     has_tcr=='True', clone_id!='') %>% 
  left_join(labels2) %>% mutate(pheno=labels2) %>% 
  select(donor_id,MDE1,MDE2,pheno,Nonviral,clone_id) %>% 
  left_join(
    read.csv('../preprocessing/data/import/Tcell-scTCR.csv') %>% filter(chain=='TRB') %>% 
      select(clone_id,CDR3aa,v_gene,j_gene) %>% distinct()
  ) %>% as_tibble() %>% 
  left_join(pois %>% mutate(is=T)) %>% mutate(is=ifelse(is.na(is),F,is))

```

Bar chart
```{r mde-scTCR-tcell, fig.height=3, fig.width=8}

dat_pl = dat %>% 
  group_by(donor_id,clone_id,is,pheno) %>% tally() %>% ungroup() %>% 
  group_by(donor_id) %>% mutate(pct=n/sum(n)*100) %>% ungroup() %>% 
  filter(is)

order = dat_pl %>% group_by(clone_id) %>% summarise(pct=sum(pct)) %>% arrange(pct) %>% .$clone_id

dat_pl %>% 
  mutate(clone_id=factor(clone_id,order)) %>% drop_na() %>% 
  ggplot(aes(clone_id,pct))+
  facet_grid(.~donor_id,space='free',scales='free')+
  geom_col(aes(fill=pheno))+
  scale_fill_manual(values = Tcell_pheno_colors)+
  guides(fill=guide_legend(ncol=2))+
  theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust=1, size=7))->pl
pl
ggsave(plot=pl,filename = '../figures/5/CARD-exp_bar.pdf',height=3,width=8, dpi="retina")

dat_pl %>% select(clone_id,donor_id) %>% distinct() %>% pull(donor_id) %>% table()
```

mde
```{r fig.height=3, fig.width=3}

clone_plot = dat[dat$is,]$clone_id

obs %>% 
  mutate(is = clone_id %in% clone_plot) %>% 
  ggplot(aes(MDE1,MDE2))+
  #geom_point(data = . %>% filter(!is), size=0.01,color='grey75',alpha=0.1)+
  scattermore::geom_scattermore(color='grey80')+
  geom_point(data = . %>% filter(is), size=1, aes(color=clone_id))+
  scale_color_manual(values = long_col_vector[1:length(clone_plot)])+
  theme_void()+
  theme(legend.position = 'none') -> pl
pl
ggsave(plot=pl,filename = '../figures/5/CARD-mde.png',width=2.5,height=2.5, dpi="retina")
```



Chi2/dotplot
```{r}
dat_pl = dat %>% 
  group_by(is,pheno) %>% tally() %>% ungroup()

out=list()
for (i in unique(dat$pheno)){
dat$i = dat$pheno==i
res = chisq.test(table(exp=dat$is, ph=dat$i))
out[[i]] = data.frame(p=res$p.value,Roe=(res$observed / res$expected)[2,2])
}
res = as_tibble(bind_rows(out,.id='pheno')) %>% 
  mutate(fdr=p.adjust(p,'BH'),sig=fdr<0.1) %>% arrange(p) 

res

```


Non-viral
```{r fig.height=3, fig.width=3.15}
#(match style of non-viral boxplot)

dat_pl = dat %>% 
  group_by(donor_id,clone_id,is) %>% summarise(Nonviral=mean(Nonviral)) %>% 
  mutate(plt = ifelse(is,'ASCT-expanded',' '))
  
dat_pl %>% 
  ggplot(aes(plt,Nonviral))+
  geom_violin(aes(fill=plt))+
  geom_boxplot(aes(fill=plt),outliers=F)+
  geom_jitter(data=. %>% filter(is),width=0.2,height=0,size=1)+
  
  scale_fill_manual(values = c('ASCT-expanded'='dodgerblue',' '='grey80'))+
  ggpubr::stat_compare_means(comparisons = list(c(' ','ASCT-expanded')),
  method = 'wilcox.test',size=3.5)+
  #ylim(c(0,0.9))+
  labs(y='Non-viral signature per-clone')+
  theme(
    axis.title.x=element_blank(),axis.text.x=element_blank(),axis.ticks.x=element_blank(),
    axis.text.y = element_text(size=11),
    axis.title.y = element_text(size=12),
  )->pl
pl
ggsave(plot=pl,filename = '../figures/5/CARD-nonviral.pdf',height=3,width=3.15, dpi="retina")

print(table(dat_pl$plt))
print(table(dat_pl$donor_id,dat_pl$plt))
lmerTest::lmer(Nonviral ~ is + (1|donor_id), dat_pl) %>% anova() %>% .[1,6]

```


## 










































