---
title: "S5"
output:
  html_document:
    code_folding: hide
    toc: true # table of content true
    toc_depth: 3  # upto three depths of headings (specified by #, ## and ###)
    number_sections: false  ## if you want number sections at each table header
params:
    args: myarg
---

## Setup

```{r setup-import, eval=T, hide=T}
library(tidyverse)
library(ggpubr)
library(RColorBrewer)
library(viridis)
source('../resources/aes.R')
range01 <- function(x){(x-min(x))/(max(x)-min(x))}
load(file = '../preprocessing/data/comp.RData')
load(file = '../preprocessing/data/ords.RData')
load(file = '../preprocessing/data/da_results.RData')
obs = read.csv('../preprocessing/data/Tcell_obs.csv')
donor_md = read.csv('../preprocessing/data/import/metadata-donor.csv')
dir.create('../figures/S5')
```

# S5A

```{r fig.height=3.5, fig.width=5.5}

comp$Tcell %>% mutate(diagnosis=cohort) %>% 
  filter(tissue=='BM', sampleSize>100) %>% 
  group_by(celltype,diagnosis,donor_id) %>% summarise(total=sum(n)) %>% 
  group_by(celltype) %>% mutate(prop=total/sum(total)*100) %>% 
  mutate(diagnosis = factor(diagnosis, levels=c('Non','MGUS','SMM','MM'))) %>% 
  arrange((prop)) %>% 
  ggplot(aes(x=celltype, y=prop, fill=diagnosis))+
  geom_bar(stat = "identity", color='black',size=0.05)+
  scale_fill_manual(values = diagnosis_col)+
  theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust=1))+
  labs(x='',y='% of cells across samples',fill='')+
  theme(
    legend.position='right',
    strip.background = element_blank()
  )-> pl
pl
ggsave(plot=pl,filename = '../figures/S5/A-left.pdf',width=5.5,height=3.5, dpi="retina")

comp$Tcell %>% 
  filter(tissue=='BM', sampleSize>100) %>% 
  group_by(celltype,study_id,donor_id) %>% summarise(total=sum(n)) %>% 
  group_by(celltype) %>% mutate(prop=total/sum(total)*100) %>% 
  arrange((prop)) %>% 
  left_join(obs %>% select(pheno,subset) %>% distinct(), by=c('celltype'='pheno')) %>% 
  ggplot(aes(x=celltype, y=prop, fill=study_id))+
  geom_bar(stat = "identity", color='black',size=0.05, alpha=0.75)+
  scale_fill_manual(values = study_colors)+
  theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust=1))+
  labs(x='',y='% of cells across samples',fill='')+
  theme(legend.position='right')+
  theme(strip.background = element_blank())-> pl
pl
ggsave(plot=pl,filename = '../figures/S5/A-right.pdf',width=5.5,height=3.5, dpi="retina")

```

# S5B

```{r fig.height=3, fig.width=3.5}

require(Cairo) #for Greek letters

# Non v MGUS
results$Tcell$cohort$addAge$Non.MGUS %>% 
  mutate(fdr = p.adjust(p.cohort,'BH')) %>% 
  mutate(sig=fdr<0.1, change=ifelse(diff>0,'up','down')) %>% 
  ggplot(aes(diff, -log10(fdr)))+
  geom_hline(yintercept = -log10(0.1), linetype='dotted', linewidth=0.5)+
  geom_vline(xintercept = 0, linewidth=0.2)+
  geom_point(color='lightgrey',alpha=0.8)+
  geom_point(data = . %>% filter(sig,change=='down'), color=disease_col['HD'])+
  geom_point(data = . %>% filter(sig,change=='up'), color=disease_col['MGUS'])+
  ggrepel::geom_text_repel(data = . %>% filter(sig), aes(label=celltype), size=3)+
  labs(x='Δ median', y='-log10 FDR', title='MGUS v Non')+
  xlim(c(-2.5,2.5))+ylim(c(0,8))+
  theme_classic()+theme(
    plot.title = element_text(hjust = 0.5, size=12),
    axis.title.x = element_text(size=13), axis.text.x = element_text(size=11),
    axis.title.y = element_text(size=13), axis.text.y = element_text(size=11)
  ) -> pl
pl
ggsave(plot=pl,filename = '../figures/S5/B-3.pdf',width=3.5,height=3, dpi="retina",device=cairo_pdf)


# Non v SMM
results$Tcell$cohort$addAge$Non.SMM %>% 
  mutate(fdr = p.adjust(p.cohort,'BH')) %>% 
  mutate(sig=fdr<0.1, change=ifelse(diff>0,'up','down')) %>% 
  ggplot(aes(diff, -log10(fdr)))+
  geom_hline(yintercept = -log10(0.1), linetype='dotted', linewidth=0.5)+
  geom_vline(xintercept = 0, linewidth=0.2)+
  geom_point(color='lightgrey',alpha=0.8)+
  geom_point(data = . %>% filter(sig,change=='down'), color=disease_col['HD'])+
  geom_point(data = . %>% filter(sig,change=='up'), color=disease_col['SMM'])+
  ggrepel::geom_text_repel(data = . %>% filter(sig), aes(label=celltype), size=3)+
  labs(x='Δ median', y='-log10 FDR', title='SMM v Non')+
  xlim(c(-2.5,2.5))+ylim(c(0,8))+
  theme_classic()+theme(
    plot.title = element_text(hjust = 0.5, size=12),
    axis.title.x = element_text(size=13), axis.text.x = element_text(size=11),
    axis.title.y = element_text(size=13), axis.text.y = element_text(size=11)
  ) -> pl
pl
ggsave(plot=pl,filename = '../figures/S5/B-2.pdf',width=3.5,height=3, dpi="retina",device=cairo_pdf)

# Non v MM
results$Tcell$cohort$addAge$Non.MM %>% 
  mutate(fdr = p.adjust(p.cohort,'BH')) %>% 
  mutate(sig=fdr<0.1, change=ifelse(diff>0,'up','down')) %>% 
  ggplot(aes(diff, -log10(fdr)))+
  geom_hline(yintercept = -log10(0.1), linetype='dotted', linewidth=0.5)+
  geom_vline(xintercept = 0, linewidth=0.2)+
  geom_point(color='lightgrey',alpha=0.8)+
  geom_point(data = . %>% filter(sig,change=='down'), color=disease_col['HD'])+
  geom_point(data = . %>% filter(sig,change=='up'), color=disease_col['MM'])+
  ggrepel::geom_text_repel(data = . %>% filter(sig), aes(label=celltype), size=3)+
  labs(x='Δ median', y='-log10 FDR', title='MM v Non')+
  xlim(c(-2.5,2.5))+ylim(c(0,8))+
  theme_classic()+theme(
    plot.title = element_text(hjust = 0.5, size=12),
    axis.title.x = element_text(size=13), axis.text.x = element_text(size=11),
    axis.title.y = element_text(size=13), axis.text.y = element_text(size=11)
  ) -> pl
pl
ggsave(plot=pl,filename = '../figures/S5/B-1.pdf',width=3.5,height=3, dpi="retina",device=cairo_pdf)


```


# S5C

```{r fig.height=3, fig.width=3.5}

require(Cairo) #for Greek letters

results$Tcell$cohort$addAge$HD.SMM %>% 
  mutate(fdr = p.adjust(p.cohort,'BH')) %>% 
  mutate(sig=fdr<0.1, change=ifelse(diff>0,'up','down')) %>% 
  ggplot(aes(diff, -log10(fdr)))+
  geom_hline(yintercept = -log10(0.1), linetype='dotted', linewidth=0.5)+
  geom_vline(xintercept = 0, linewidth=0.2)+
  geom_point(color='lightgrey',alpha=0.8)+
  geom_point(data = . %>% filter(sig,change=='down'), color=disease_col['HD'])+
  geom_point(data = . %>% filter(sig,change=='up'), color=disease_col['SMM'])+
  ggrepel::geom_text_repel(data = . %>% filter(sig), aes(label=celltype), size=3)+
  labs(x='Δ median', y='-log10 FDR', title='SMM v HD')+
  xlim(c(-2.5,2.5))+ylim(c(0,8))+
  theme_classic()+theme(
    plot.title = element_text(hjust = 0.5, size=12),
    axis.title.x = element_text(size=13), axis.text.x = element_text(size=11),
    axis.title.y = element_text(size=13), axis.text.y = element_text(size=11)
  ) -> pl
pl
ggsave(plot=pl,filename = '../figures/S5/C-1.pdf',width=3.5,height=3, dpi="retina",device=cairo_pdf)


results$Tcell$cohort$addAge$HD.MM %>% 
  mutate(fdr = p.adjust(p.cohort,'BH')) %>% 
  mutate(sig=fdr<0.1, change=ifelse(diff>0,'up','down')) %>% 
  ggplot(aes(diff, -log10(fdr)))+
  geom_hline(yintercept = -log10(0.1), linetype='dotted', linewidth=0.5)+
  geom_vline(xintercept = 0, linewidth=0.2)+
  geom_point(color='lightgrey',alpha=0.8)+
  geom_point(data = . %>% filter(sig,change=='down'), color=disease_col['HD'])+
  geom_point(data = . %>% filter(sig,change=='up'), color=disease_col['MM'])+
  ggrepel::geom_text_repel(data = . %>% filter(sig), aes(label=celltype), size=3)+
  labs(x='Δ median', y='-log10 FDR', title='MM v HD')+
  xlim(c(-2.5,2.5))+ylim(c(0,8))+
  theme_classic()+theme(
    plot.title = element_text(hjust = 0.5, size=12),
    axis.title.x = element_text(size=13), axis.text.x = element_text(size=11),
    axis.title.y = element_text(size=13), axis.text.y = element_text(size=11)
  ) -> pl
pl
ggsave(plot=pl,filename = '../figures/S5/C.pdf',width=3.5,height=3, dpi="retina",device=cairo_pdf)

```

# S5D

```{r fig.height=3, fig.width=3.5}

require(Cairo) #for Greek letters

results$Tcell$cohort$addAge$SMM.MM %>% 
  mutate(fdr = p.adjust(p.cohort,'BH')) %>% 
  mutate(sig=fdr<0.1, change=ifelse(diff>0,'up','down')) %>% 
  ggplot(aes(diff, -log10(fdr)))+
  geom_hline(yintercept = -log10(0.1), linetype='dotted', linewidth=0.5)+
  geom_vline(xintercept = 0, linewidth=0.2)+
  geom_point(color='lightgrey',alpha=0.8)+
  geom_point(data = . %>% filter(sig,change=='down'), color=disease_col['SMM'])+
  geom_point(data = . %>% filter(sig,change=='up'), color=disease_col['MM'])+
  ggrepel::geom_text_repel(data = . %>% filter(sig), aes(label=celltype), size=3)+
  labs(x='Δ median', y='-log10 FDR', title='SMM v MM')+
  xlim(c(-2.5,2.5))+ylim(c(0,8))+
  theme_classic()+theme(
    plot.title = element_text(hjust = 0.5, size=12),
    axis.title.x = element_text(size=13), axis.text.x = element_text(size=11),
    axis.title.y = element_text(size=13), axis.text.y = element_text(size=11)
  ) -> pl
pl
ggsave(plot=pl,filename = '../figures/S5/D.pdf',width=3.5,height=3, dpi="retina",device=cairo_pdf)

```



# S5G

PCA
```{r fig.height=3, fig.width=4.5}

pc1.pct = pct.expl = round(summary(ords$Tcell)[["cont"]][["importance"]]['Proportion Explained','PC1'],4)*100
pc2.pct = pct.expl = round(summary(ords$Tcell)[["cont"]][["importance"]]['Proportion Explained','PC2'],4)*100

dat = ords$Tcell$PCA %>% 
  left_join(comp$Tcell %>% select(sample_id,cohort) %>% distinct()) %>% 
  mutate(cohort=factor(cohort,c('Non','MGUS','SMM','MM')))

pca.mean = dat %>% select(PC1,PC2,cohort) %>% group_by(cohort) %>% summarise_all(mean)

# Explaned variance

dat %>% ggplot(aes(PC1,PC2))+
  geom_point(aes(color=cohort),show.legend=F)+
  scale_color_manual(values=diagnosis_col)+
  scale_fill_manual(values=diagnosis_col)+
  scale_shape_manual(values=rep(19,5))+
  geom_rug(aes(color=cohort),alpha=0.8,show.legend=F)+
  geom_point(
    data = pca.mean, aes(PC1,PC2,fill=cohort), size=5, shape=21, alpha=0.75
  )+
  labs(fill='')+
  theme_classic()+
  theme(
    legend.position = 'right',
    plot.title = element_text(hjust = 0.5),
    axis.title.x = element_text(size=13), 
    axis.text.x = element_text(size=11),
    axis.title.y = element_text(size=13), 
    axis.text.y = element_text(size=13)
  )+
  labs(x=paste0('PC1 (',pc1.pct,'%)'),y=paste0('PC2 (',pc2.pct,'%)'))-> pl
pl
ggsave(plot=pl,filename = '../figures/S5/G-left.pdf',width=4.5,height=3, dpi="retina")


```

Elbow
```{r fig.height=1.5, fig.width=2.5}

data.frame(summary(ords$Tcell)[["cont"]][["importance"]])['Proportion Explained',] %>% 
  t() %>% data.frame() %>% rownames_to_column('PC') %>% 
  mutate(i = as.numeric(str_remove(PC,'PC'))) %>% 
  head(5) %>% 
  arrange(i) %>% mutate(PC=factor(PC,PC)) %>% 
  ggplot(aes(PC,Proportion.Explained*100))+
  geom_line(aes(group=1))+geom_point()+
  labs(y='% variance\nexplained')+
  theme(
    axis.text.x = element_text(angle = 45, vjust = 1, hjust=1, size=11),
    axis.title.x = element_blank()
  ) -> pl
pl
ggsave(plot=pl,filename = '../figures/S5/G-right.pdf',width=2.5,height=1.5, dpi="retina")

```


# S5H

```{r fig.width=3, fig.height=3}

dat = ords$Tcell$PCA %>% 
  left_join(comp$Tcell %>% select(sample_id,cohort,age) %>% distinct()) %>% 
  mutate(diagnosis=cohort) %>% filter(!is.na(age)) %>% 
  mutate(cohort=factor(cohort,c('Non','MGUS','SMM','MM')))

mod=lm(PC1 ~ age,dat)

dat %>% 
  ggplot(aes(age,PC1))+geom_point(size=1.5, aes(color=diagnosis))+
  #geom_abline(intercept=mod$coefficients[1], slope=mod$coefficients[2], 
  #            color='black', linetype='dashed', size=1)+
  geom_smooth(color='black', method='lm',size=1, se=T,linetype='dashed')+
  scale_color_manual(values=diagnosis_col)+scale_fill_manual(values=diagnosis_col)+
  scale_y_continuous(breaks=c(-0.2,-0.1,0,0.1,0.2))+
  ggpubr::stat_cor(label.y = -0.2)+
  labs(x='Age',y='T cell skewing')+
  theme_classic()+theme(legend.position = "none",
    axis.title.x = element_text(size=14), axis.text.x = element_text(size=12),
    axis.title.y = element_text(size=14), axis.text.y = element_text(size=12)
  )-> pl
pl
ggsave(plot=pl,filename = '../figures/S5/H.pdf',width=3,height=3, dpi="retina")
```

## SPACE 










































































































