---
title: "S6"
output:
  html_document:
    code_folding: hide
    toc: true # table of content true
    toc_depth: 3  # upto three depths of headings (specified by #, ## and ###)
    number_sections: false  ## if you want number sections at each table header
params:
    args: myarg
---

```{r}
'../integration/data/validation/Tcell2_validT_run1-obs.csv'

#valid_comp = 
#valid_ords = 


# mkdir/save figures to
dir.create('../figures/S6')
'../figures/S6'

```


## Setup

```{r setup-import, eval=T, hide=T}

library(tidyverse)
library(ggpubr)
library(RColorBrewer)
library(viridis)
source('aes.R')
range01 <- function(x){(x-min(x))/(max(x)-min(x))}
load(file = 'data/abundances/abundances.RData')
load(file = 'data/ordination/ords.RData')
donors.longit = c("COSMOS22:C035","COSMOS22:C018",'COSMOS22:C005','Liu2021:37692_SMM','Liu2021:47491_SMM ','Liu2021:58408_SMM','oetjen2018:C_T2','oetjen2018:S_T2')

# obs
#obs = read.csv('data/obs/Tcell.csv') %>% filter(!subset %in% c('DN','QC','CD3_neg'))
#read.csv('data/obs/Tcell-pheno-merge.csv')
obs = read.csv('data/validation_data/Tcell2_validT_run1-obs.csv') %>% 
  left_join(read.csv('data/validation_data/Tcell2_validT_run1.csv')) %>% 
  filter(study=='Botta2023') %>% 
  filter(!pheno_pred %in% c('Unknown','Myeloid','CD3_neg','Doublet')) 

obs = obs %>% filter(pheno_pred %in% names(table(obs$pheno_pred)[table(obs$pheno_pred)>10]))

# md 
md = as_tibble(read.csv('data/validation_data/validation-metadata.csv'))
valid_names_neat=data.frame(study=c('Botta2023','Lasry2023'),
                            name_neat=c('Botta et al. (2023)','Lasry et al (2023)'))

# comp
thr=0.2 #as recommended
valid_comp = read.csv(paste0('data/validation_data/comp-CertThr',thr,'.csv')) %>% as_tibble()
# ords
pca = read.csv(paste0('data/validation_data/pca-CertThr',thr,'.csv')) %>% as_tibble()

# scores
load(file='data/validation_data/validT_20240212-gsT.RData') #scr

```





## Schematic mde

```{r fig.height=2, fig.width=2}

obs %>% 
  ggplot(aes(X_mde1,X_mde2))+
  geom_point(size=0.01, color='grey70')+
  coord_fixed()+
  theme_void()+
  theme(legend.position = 'none')-> pl
pl
ggsave(plot=pl,filename = 'figures/Valid/mde-schem.png',width=2,height=2, dpi="retina")

```

## Phenotype mde


```{r fig.height=3, fig.width=3}

obs.pl = obs %>% mutate(pheno_pred = factor(pheno_pred, names(Tcell_pheno_colors))) 
obs.pl.med = obs.pl %>% select(pheno_pred,X_mde1,X_mde2) %>% 
  group_by(pheno_pred) %>% summarise_all(.funs = median)

obs.pl %>% 
  ggplot(aes(X_mde1,X_mde2))+
  geom_point(size=0.1,aes(color=pheno_pred))+coord_fixed()+theme_void()+
  #ylim(c(-3,3))+xlim(c(-3,3))+
  #ggrepel::geom_text_repel(data = obs.pl.med, size=3, box.padding = 1, aes(label=pheno_pred), force=10)+
  geom_point(data = obs.pl.med, shape=21, aes(fill=pheno_pred), size=4)+
  scale_color_manual(values = Tcell_pheno_colors)+scale_fill_manual(values = Tcell_pheno_colors)+
  guides(color=guide_legend(ncol=3,override.aes = list(size=3)))+
  theme(legend.position = 'none')-> pl
pl
ggsave(plot=pl,filename = 'figures/Valid/mde-pheno.png',width=3,height=3, dpi="retina")

```

Legend
```{r fig.height=2.2, fig.width=1.25}

obs.pl.med %>% mutate(pheno_pred=factor(pheno_pred,rev(Tcell_order))) %>% 
  mutate(pheno=replace(pheno_pred,pheno_pred=='Treg','CD4.Treg')) %>% 
  ggplot(aes(1,0,fill=pheno_pred))+
  geom_bar(stat='identity',width=0)+
  scale_fill_manual(values=Tcell_pheno_colors)+
  guides(fill = guide_legend(ncol=1, label.position = "left",label.hjust = 1))+
  theme_void()+
  theme(
    legend.title=element_blank(),
    legend.key.size = unit(0.4, "cm"),
    legend.text=element_text(size=10),
  )->pl
pl = ggpubr::as_ggplot(ggpubr::get_legend(pl))
pl
ggsave(plot=pl,filename = 'figures/Valid/umap-legend.pdf',width=1.25,height=2.2, dpi="retina")

```



## Diagnosis mde

```{r fig.height=5, fig.width=5}

dat = obs %>% filter(study=='Botta2023') %>% 
  filter(!pheno_pred %in% c('Unknown','Myeloid','CD3_neg','Doublet')) %>% 
  left_join(md %>% select(sample_id,diagnosis)) %>% 
  left_join(
    md %>% filter(study=='Botta2023',sample_id %in% obs$sample_id) %>% select(diagnosis,sample_id) %>% 
    distinct() %>% group_by(diagnosis) %>% tally()) %>% 
  mutate(diagnosis = factor(diagnosis, names(diagnosis_col))) %>% 
  mutate(diagnosis_n=paste0(diagnosis,'\nn = ',n)) %>% 
  arrange(diagnosis) %>% mutate(diagnosis_n=factor(diagnosis_n,unique(diagnosis_n)))

dat %>% 
  group_by(diagnosis) %>% sample_n(min(table(dat$diagnosis)[table(dat$diagnosis)>0])) %>% 
  ggplot(aes(X_mde1,X_mde2,color=diagnosis))+
  geom_point(size=0.1)+
  labs(color='')+
  facet_wrap('diagnosis_n')+
  coord_fixed()+theme_void()+
  scale_color_manual(values = diagnosis_col)+
  guides(color=guide_legend(override.aes = list(size=3)))+
  theme(
    legend.position='none',strip.text.x = element_text(size=15),
  )-> pl
pl
#ggsave(plot=pl,filename = 'figures/Valid/mde-BottaDiag.png',width=5,height=5, dpi="retina")

```


## Dotplot markers

Prep
```{r}

markers = read.csv('data/expression/markers.csv') %>% filter(plot=='panT_pl')

dat = read.csv('data/validation_data/expression.csv') %>% left_join(obs %>% select(X,study,pheno_pred)) %>% 
  filter(!is.na(pheno_pred),pheno_pred!='Unknown') %>% 
  select(-X) %>% 
  rename(pheno=pheno_pred) %>% 
  filter(!pheno %in% c('Doublet','CD3_neg','Myeloid')) 
  
# Prep per-study
dat.sum = dat %>% 
  group_by(study,pheno) %>% summarise_all(.funs = mean) %>% 
  pivot_longer(!study:pheno,names_to='gene',values_to='mean') %>% 
  group_by(study,gene) %>% mutate(mean=range01(mean)) %>% ungroup() %>% 
  left_join(
    dat %>% 
      group_by(study,pheno) %>% summarise_all(.funs = function(i){sum(i>0)/length(i)*100}) %>% 
      pivot_longer(!study:pheno,names_to='gene',values_to='pct_exp')
  ) %>% 
  left_join(markers %>% select(gene,gene_group)) %>% filter(!is.na(gene_group)) %>% 
  mutate(gene=factor(gene,markers$gene)) %>% 
  mutate(gene_group=factor(gene_group,unique(markers$gene_group))) %>% 
  mutate(pheno=replace(pheno,pheno=='Treg','CD4.Treg')) %>% 
  left_join(data.frame(pheno=Tcell_order,subset=Tcell_subsets)) %>% 
  mutate(pheno = factor(pheno,rev(Tcell_order))) %>% 
  mutate(subset = factor(subset,c('CD4+','CD8+','Other')))

```

Botta 2023
```{r fig.height=3.5, fig.width=10.25}

dat.sum %>% filter(study=='Botta2023') %>% 
  ggplot(aes(gene,pheno))+
  geom_point(aes(fill=mean,size=pct_exp),shape=21)+
  scale_fill_distiller(palette = 'Reds',trans = "reverse")+
  facet_grid(subset~gene_group,scales='free',space='free')+
  scale_size(range = c(0.75,4.5))+
  labs(x='',y='')+
  theme_bw()+
  theme(
    legend.position = 'none',
    plot.title = element_text(hjust = 0.5, size=12),
    #whole plot
    axis.text.x = element_text(angle = 90, vjust = 0, hjust=1),
    panel.grid.major.x=element_blank(),panel.grid.minor.x=element_blank(),
    #facet boxes    
    strip.text.x = element_text(face = 'bold',size=8),
    strip.text.y = element_text(angle = 0,face = 'bold',size=8),
    strip.background = element_blank(),
    panel.spacing = unit(0, "lines")
  )-> pl
pl
ggsave(plot=pl,filename = 'figures/Valid/dot_markers-Botta.pdf',width=10.2,height=3.5, dpi="retina")

```




## Marker mde

```{r fig.height=4, fig.width=4}

dat = read.csv('data/validation_data/expression.csv') %>% 
  left_join(obs %>% select(X,sample_id,X_mde1,X_mde2,study,pheno_pred)) %>% 
  filter(!pheno_pred %in% c('Doublet','CD3_neg','Myeloid')) %>% 
  left_join(scater::makePerCellDF(scr,c('Chu2023_Cytotoxicity','Chu2023_Naive'),assay.type='scores') %>%
            mutate(X=colnames(scr)) %>% select(X,Chu2023_Cytotoxicity,Chu2023_Naive)) %>% 
  select(X,X_mde1,X_mde2,CD4,CD8A,Chu2023_Cytotoxicity,Chu2023_Naive)

# Plot
dat %>% 
  pivot_longer(!X:X_mde2) %>% 
  group_by(name) %>% mutate(value=range01(value)) %>% 
  mutate(name=replace(name,name=='Chu2023_Cytotoxicity','Cytotoxicity score')) %>% 
  mutate(name=replace(name,name=='Chu2023_Naive','Naive score')) %>% 
  mutate(name=factor(name,levels=c('CD4','CD8A','Naive score','Cytotoxicity score'))) %>% 
  ggplot(aes(X_mde1,X_mde2))+
  facet_wrap('name',ncol=2)+
  geom_point(data = . %>% filter(value==0), aes(color=value), size=0.01)+
  geom_point(data = . %>% filter(value>0), aes(color=value), size=0.01)+
  scale_color_distiller(palette = 'Reds',direction = 1)+
  theme_void()+
  theme(legend.position = 'none',strip.text.x = element_text(size = 15))->pl
pl

#TURN OFF CLIPPING
pg=ggplot2::ggplotGrob(pl)
for(i in which(grepl("strip-t", pg$layout$name))){pg$grobs[[i]]$layout$clip <- "off"}
ggsave(plot=pg,filename = 'figures/Valid/umap-markers.png',width=4,height=4, dpi="retina")

```




## Boxplots

PCA - all cohorts atlas/botta
```{r fig.width=2.75, fig.height=3}

pca %>% left_join(md %>% select(sample_id,study,diagnosis)) %>% filter(study=='Botta2023') %>% 
  mutate(source='Botta et al.') %>% 
  select(source,sample_id,diagnosis,PC1) %>% 
  rbind(ords$tc$pheno$PCA %>% left_join(comp$da_md) %>% mutate(source='Full dataset') %>%
          select(source,sample_id,diagnosis,PC1) %>% distinct()
  ) %>% 
  mutate(source=factor(source,c('Full dataset','Botta et al.'))) %>% 
  #scale by source
  group_by(source) %>% mutate(PC1=scale(PC1)) %>% 

  mutate(diagnosis=factor(diagnosis,c('Non','MGUS','SMM','MM'))) %>%
  
  #ggplot(aes(x = diagnosis, y = PC1, fill=diagnosis))+facet_grid(~source)+
  ggplot(aes(x = source, y = PC1, fill=diagnosis))+facet_grid(~diagnosis)+
  
  geom_boxplot(outlier.alpha = 0)+
  geom_jitter(width=0.2,height=0,size=0.25)+

  ggpubr::stat_compare_means(data=. %>% filter(diagnosis=='Non'),comparisons=list(c('Full dataset','Botta et al.')),size=3.5,label.y=3)+
  ggpubr::stat_compare_means(data=. %>% filter(diagnosis=='MGUS'),comparisons=list(c('Full dataset','Botta et al.')),size=3.5,label.y=3)+
  ggpubr::stat_compare_means(data=. %>% filter(diagnosis=='SMM'),comparisons=list(c('Full dataset','Botta et al.')),size=3.5,label.y=3)+
  ggpubr::stat_compare_means(data=. %>% filter(diagnosis=='MM'),comparisons=list(c('Full dataset','Botta et al.')),size=3.5,label.y=3)+
  
  ylim(c(-3.1,4))+
  
  scale_fill_manual(values=diagnosis_col)+
  labs(title='',y='T cell skewing')+
  theme(
    legend.position='none',
    axis.text.x = element_text(angle = 45, vjust = 1, hjust=1), axis.title.x=element_blank(),
    plot.title = element_text(hjust = 0.5, size=12),
    strip.background = element_blank(),
    axis.title.y = element_text(size=11), axis.text.y = element_text(size=11)
  )-> pl
pl
ggsave(plot=pl,filename = 'figures/Valid/box-PC1.pdf',width=2.75,height=3, dpi="retina")

```

CD8.TemTerm, atlas & botta
```{r fig.width=1.5, fig.height=3}

#All Non vs Botta every diagnosis

valid_comp %>% left_join(md %>% select(sample_id,study,diagnosis)) %>% 
  filter(study=='Botta2023') %>% 
  rename(source=study) %>% 
  select(source,diagnosis,celltype,clr) %>% 
  rbind(comp$tc$ph %>% 
    filter(tissue=='BM', sampleSize>100,sample_id!='zhang2021:MM-P20190122-T') %>%  
    mutate(source='atlas') %>% select(source,diagnosis,celltype,clr)) %>% 
  mutate(source_diag = paste0(source,'_',diagnosis)) %>% 
  filter(source_diag %in% c('atlas_Non','atlas_MM','Botta2023_MM')) %>% 
  
  left_join(data.frame(
    source_diag = c('atlas_Non','atlas_MM','Botta2023_MM'),
    source_diag_pl = c('Non (full dataset)','MM (full dataset)','MM (Botta et al.)') 
  )) %>% mutate(source_diag=source_diag_pl) %>% 
  
  mutate(source_diag=factor(source_diag,
    c('Non (full dataset)','MM (full dataset)','MM (Botta et al.)'))) %>% 
  filter(celltype %in% c('CD8.TemTerm')) %>% #,'CD8.TemActive','CD4.Tn','CD4.Tem','CD8.Tn')) %>% 
  
  filter(diagnosis %in% c('Non','MM')) -> dat

dat %>% 
  ggplot(aes(x = source_diag, y = clr, fill=diagnosis))+
  geom_boxplot(outlier.alpha = 0)+
  geom_jitter(width=0.2,height=0,size=0.2)+
  
  ggpubr::stat_compare_means(comparisons = list(
    c('Non (full dataset)','MM (full dataset)'),
    c('Non (full dataset)','MM (Botta et al.)'),
    c('MM (full dataset)','MM (Botta et al.)')),
  method = 'wilcox.test',size=3.25)+
  scale_fill_manual(values=diagnosis_col)+
  labs(y='Normalised % T cells)',title='CD8.TemTerm')+
  ylim(c(-2.1,6.5))+
  theme_classic()+
  theme(
    legend.position='none',
    axis.text.x = element_text(angle = 45, vjust = 1, hjust=1, size=10),
    axis.title.x=element_blank(),
    plot.title = element_text(hjust = 0.5, size=11),
    axis.title.y = element_text(size=11), axis.text.y = element_text(size=11)
  )-> pl
pl
ggsave(plot=pl,filename = 'figures/Valid/box-TemTerm.pdf',width=1.5,height=3, dpi="retina")
```





# SPACE 








































































































