---
title: "S7"
output:
  html_document:
    code_folding: hide
    toc: true # table of content true
    toc_depth: 3  # upto three depths of headings (specified by #, ## and ###)
    number_sections: false  ## if you want number sections at each table header
params:
    args: myarg
---

## Setup

```{r setup-import, eval=T, hide=T}

library(tidyverse)
library(ggpubr)
library(RColorBrewer)
library(viridis)
source('../resources/aes.R')
range01 <- function(x){(x-min(x))/(max(x)-min(x))}
load(file = '../preprocessing/data/comp.RData')
load(file = '../preprocessing/data/ords.RData')
load(file = '../preprocessing/data/tcr_analysis.RData')
obs = read.csv('../preprocessing/data/Tcell_obs.csv')
tcr = read.csv('../preprocessing/data/import/Tcell-scTCR.csv')
donor_md = read.csv('../preprocessing/data/import/metadata-donor.csv')
dir.create('../figures/S7')

```

## S7A

```{r fig.width=3.5, fig.height=2.5}

tcr %>% 
  ggplot(aes(CD4_Ncells+1,CD8_Ncells+1,fill=type))+
  geom_abline(slope=1, intercept=0)+
  labs(x='log10[N+1] cells CD4 detected',y='log10[N+1] cells CD8 detected',fill='Clone\nsubset')+
  geom_point(size=1.5,shape=21)+scale_x_log10()+scale_y_log10()+
  scale_fill_brewer(palette = 'Dark2')-> pl
pl
ggsave(plot=pl, filename = '../figures/S7/A-left.png',width=3.5,height=2.5, dpi="retina")

```


```{r fig.width=6.5, fig.height=2}

obs %>% left_join(tcr %>% select(clone_id,type)) %>% 
  filter(!is.na(type)) %>% 
  ggplot(aes(MDE1,MDE2,color=type))+facet_grid(~type)+
  scattermore::geom_scattermore()+
  scale_color_brewer(palette = 'Dark2')+
  theme_void()+theme(legend.position = 'none',strip.text.y = element_text(size = 14))-> pl
pl
ggsave(plot=pl,filename = '../figures/S7/A-right.png',width=6.5,height=2, dpi="retina")

```


## S7B

```{r fig.height=2.5, fig.width=2.5}

th = theme(legend.position = "none",
  plot.title = element_text(hjust = 0.5, size=12),
  axis.text.x = element_text(size=11),axis.title.x = element_text(size=13),
  axis.text.y = element_text(size=11),axis.title.y = element_text(size=13))

div = tcr_analysis$clonality %>% 
  mutate(cohort = replace(cohort, cohort=='MGUS', 'SMM')) %>% 
  filter(! donor_id %in% donors.longit) #same as DA!

#CD8+Tm
div %>% filter(cohort=='Non',group=='CD8.Tm') %>% 
  left_join(ords$Tcell$PCA %>% 
    left_join(comp$Tcell %>% select(sample_id,donor_id) %>% distinct())) %>% 
  ggplot(aes(PC1,clon))+geom_point(size=1, aes(color=cohort))+
  geom_smooth(method='lm',size=1,alpha=0.2, color='grey20')+
  ggpubr::stat_cor(label.sep='\n',label.x= -0.05, label.y = -0.75)+
  scale_color_manual(values=diagnosis_col)+scale_fill_manual(values=diagnosis_col)+
  labs(x='PC1',y='Clonality',title='CD8+ memory')+theme_classic()+th-> pl
pl
ggsave(plot=pl,filename = '../figures/S7/B.pdf',width=2.5,height=2.5, dpi="retina")

```

## S7C

```{r, eval=T, hide=T, fig.height=4, fig.width=8}
dat.ph = tcr_analysis$clus$pheno %>% 
  # >1 clone
  filter(clus_id %in% tcr_analysis$clus$Nclone[tcr_analysis$clus$Nclone$exp,]$clus_id) %>% 
  group_by(clus_id,pheno) %>% summarise(n=sum(n)) %>% ungroup() %>% 
  group_by(clus_id) %>% mutate(pct=n/sum(n)*100) %>% 
  select(clus_id,pheno,pct) %>% 
  pivot_wider(names_from='clus_id',values_from='pct',values_fill=0) %>% 
  as.data.frame() %>% column_to_rownames('pheno')

# Column donor md
clus_id.md = data.frame(clus_id=colnames(dat.ph)) %>% 
  left_join(
    tcr_analysis$clus$pheno %>% ungroup() %>% select(clus_id,donor_id) %>% distinct() %>%
      left_join(donor_md %>% select(donor_id,cohort)) %>% distinct() %>% 
      dplyr::rename(Cohort='cohort')
  ) %>% 
  #Donor
  dplyr::rename(Donor='donor_id') %>% 
  #A/B
  left_join(tcr_analysis$clus$clus_id %>% 
    select(clus_id,chain) %>% distinct()) %>% dplyr::rename(Chain='chain') %>% 
  mutate(Chain=ifelse(Chain=='TRA','Alpha','Beta')) %>% 
  #Clones
  left_join(tcr_analysis$clus$Nclone) %>% mutate(Clones = n) %>% select(-n,-exp) %>% 
  #N cells
  #left_join(clone_id.clus_id.ph %>% group_by(clus_id) %>% summarise(Cells=sum(n))) %>% 
  data.frame() %>% column_to_rownames('clus_id')

# Donor color palette
library(RColorBrewer)
n <- length(unique(clus_id.md$Donor))
qual_col_pals = brewer.pal.info[brewer.pal.info$category == 'qual',]
col_vector = unlist(mapply(brewer.pal, qual_col_pals$maxcolors, rownames(qual_col_pals)))
donor_cols=setNames(col_vector[1:n],unique(clus_id.md$Donor))

# md col
annot_col = list(
  Clones = c("grey90", "firebrick"), 
  #Cells = c("grey90", "firebrick"),
  Chain = c('Alpha'='pink','Beta'='skyblue'),
  Cohort=diagnosis_col[c('Non','MGUS','SMM','MM')],
  Donor=donor_cols
)

#pl
dat.ph %>% pheatmap::pheatmap(
  show_colnames = F, border_color=NA,
  color=viridis::cividis(50,direction=1),
  annotation_col = clus_id.md,
  annotation_colors= annot_col,
  treeheight_row = 20, treeheight_col = 20
)-> ph

save_pheatmap_pdf(ph, "../figures/S6/C.pdf", height=4, width = 8)

```


## S7D

```{r, eval=T, hide=T, fig.height=2.5, fig.width=2}

tcr.exp = tcr %>% group_by(clone_id) %>% tally() %>% filter(n>1)

tcr %>% 
  filter(clone_id %in% tcr.exp$clone_id) %>% 
  mutate(id=paste0(CDR3aa,v_gene,j_gene)) %>% 
  select(donor_id,chain,id) %>% distinct() %>% 
  group_by(donor_id,chain) %>% tally() %>% arrange(n) %>% 
  ggplot(aes('',n))+geom_boxplot(outliers = F)+scale_y_log10(breaks=c(1,10,100,1000))+
  facet_grid(~chain)+
  geom_jitter(width=0.2,height=0,size=0.5)+
  labs(x='N input chains\nper donor',y="Counts") -> pl
pl
ggsave(plot=pl,filename = '../figures/S7/D-1.pdf',height=2.5,width=2, dpi="retina")

tcr_analysis$clus$pheno %>% ungroup() %>% select(donor_id,clus_id) %>% distinct() %>% 
  group_by(donor_id) %>% tally() %>% arrange(n) %>% 
  ggplot(aes('',n))+geom_boxplot()+scale_y_log10(breaks=c(1,10))+
  geom_jitter(width=0.2,height=0,size=0.5)+
  labs(x='N clusters\nper donor',y='Counts',title='') -> pl
pl
ggsave(plot=pl,filename = '../figures/S7/D-2.pdf',height=2.5,width=1, dpi="retina")

```


## S7E

Boxplot, counts per individual
```{r fig.height=2.25, fig.width=1.75}

viral_hits = read.csv('../resources/viral_hits.csv')

obs %>% filter(donor_id %in% viral_hits$donor_id) %>% 
  left_join(viral_hits %>% select(clone_id,hit)) %>% 
  mutate(hit=ifelse(!is.na(hit),'Viral','None')) %>% 
  group_by(donor_id,hit) %>% tally() %>% 
  ggplot(aes(hit,n))+
  geom_boxplot(outlier.alpha = 0)+geom_point()+geom_line(aes(group=donor_id))+
  scale_y_log10()+
  labs(x='Annotation', y='Counts per patient repertoire')+
  theme(axis.title.y=element_text(size=10))-> pl
pl
ggsave(plot=pl,filename = '../figures/S7/E-1.pdf',width=1.75,height=2.25, dpi="retina")

```

Bar chart
```{r fig.height=4, fig.width=6}

viral_hits = read.csv('../resources/viral_hits.csv')
#%>% filter(hit=='2match') #much more Tem-specific mapping vs Tn

CD8.Tem = c("CD8.TemActive","CD8.TEMRA","CD8.TemTerm","CD8.Tem.IL7R","CD8.Tem.KLRG1","CD8.Trm",      "CD8.Tex")

dat = obs %>% filter(donor_id %in% viral_hits$donor_id, clone_id!='') %>% 
  left_join(viral_hits %>% select(clone_id,hit,annot)) %>% filter(!is.na(hit)) %>% 
  select(pheno,clone_id,annot) %>% distinct() %>% 
  mutate(pheno=ifelse(pheno %in% CD8.Tem,'CD8.Tem',pheno)) %>% 
  group_by(pheno,annot) %>% tally() 

ph.order = dat %>% group_by(pheno) %>% summarise(n=sum(n)) %>% arrange(n) %>% pull(pheno)

tot.pl =  dat %>% group_by(pheno) %>% summarise(n=sum(n)) %>% 
  left_join(
    obs %>% filter(donor_id %in% viral_hits$donor_id, clone_id!='') %>% 
        mutate(pheno=ifelse(pheno %in% CD8.Tem,'CD8.Tem',pheno)) %>% 
        group_by(pheno) %>% tally(name='total') )

dat %>% mutate(pheno=factor(pheno,ph.order)) %>% 
  ggplot(aes(n,pheno))+
  geom_col(aes(fill=annot))+
  geom_point(data = tot.pl, aes(size=total), shape=21)+
  scale_fill_brewer(palette = 'Set2')+
  labs(size='Total unique',fill='Annotation',x='N annotated',y='')-> pl
pl
ggsave(plot=pl,filename = '../figures/S7/E-2.pdf',width=5,height=3, dpi="retina")

```

MDE
```{r fig.height=3, fig.width=4}
dat = obs %>% filter(donor_id %in% viral_hits$donor_id, clone_id!='') %>% 
  left_join(viral_hits %>% select(clone_id,hit,annot)) %>% 
  left_join(labels2) %>% mutate(pheno=labels2)

#expanded >1
dat = dat %>% filter(clone_id %in% 
  (dat %>% group_by(clone_id) %>% tally() %>% filter(n>1) %>% pull(clone_id)))

dat.sum = dat %>% filter(!is.na(annot)) %>% group_by(clone_id,annot) %>% 
  summarise(n=n(),MDE1=median(MDE1),MDE2=median(MDE2)) %>% 
  mutate(annot = factor(annot,rev(c("SARS-CoV-2","InfluenzaA","EBV","CMV"))))

dat %>% 
  ggplot(aes(MDE1,MDE2))+
  geom_point(data = . %>% filter(is.na(annot)), size=0.1, color='grey80',alpha=0.2)+
  geom_point(data = dat.sum, aes(size=n,color=annot))+
  scale_size_continuous(range = c(0.5,5))+
  scale_color_brewer(palette = 'Dark2')+
  theme_void()+theme(legend.position = 'right')-> pl
pl
ggsave(plot=pl,filename = '../figures/S7/E-mde.png',width=4,height=3, dpi="retina")
ggsave(plot=pl,filename = '../figures/S7/E-mde.pdf',width=4,height=3, dpi="retina")

```





## S7F

```{r fig.height=3, fig.width=2.5}
viral_hits = read.csv('../resources/viral_hits.csv')

dat = obs %>% filter(donor_id %in% viral_hits$donor_id) %>% 
  filter(clone_id!='') %>% 
  left_join(viral_hits %>% select(clone_id,hit)) %>% 
  mutate(annot=ifelse(!is.na(hit),'Viral','None')) %>% 
  group_by(clone_id,annot) %>% summarise(n=n(),Nonviral=mean(Nonviral)) %>% 
  drop_na()

dat %>% filter(n>1) %>% mutate(annot=factor(annot,c('Viral','None'))) %>% 
  ggplot(aes(annot,Nonviral))+
  geom_violin(aes(fill=annot))+
  geom_boxplot(aes(fill=annot),outliers=F)+
  scale_fill_manual(values = c('None'='dodgerblue','Viral'='grey80'))+
  labs(x='Annotation', y='Mean non-viral specificty\nsignature per-clone')+
  ggtitle('All expanded (>1)')+
  ylim(c(0,0.85))+
  ggpubr::stat_compare_means(comparisons = list(c('None','Viral')))+
  theme(plot.title = element_text(hjust = 0.5, size=10),axis.title.x=element_blank())-> pl
pl
ggsave(plot=pl,filename = '../figures/S7/F-1.pdf',width=2.5,height=3, dpi="retina")


dat %>% filter(n>5) %>% mutate(annot=factor(annot,c('Viral','None'))) %>% 
  ggplot(aes(annot,Nonviral))+
  geom_violin(aes(fill=annot))+
  geom_boxplot(aes(fill=annot),outliers=F)+
  scale_fill_manual(values = c('None'='dodgerblue','Viral'='grey80'))+
  labs(x='Annotation', y='Mean non-viral specificty\nsignature per-clone')+
  ggtitle('Highly expanded (>5)')+
  ylim(c(0,0.85))+
  ggpubr::stat_compare_means(comparisons = list(c('None','Viral')))+
  theme(plot.title = element_text(hjust = 0.5, size=10),axis.title.x=element_blank())-> pl
pl
ggsave(plot=pl,filename = '../figures/S7/F-2.pdf',width=2.5,height=3, dpi="retina")

dat %>% filter(n>1) %>% mutate(annot=factor(annot,c('Viral','None'))) %>% pull(annot) %>% table()
```

```{r fig.height=3, fig.width=4}
viral_hits = read.csv('../resources/viral_hits.csv')

dat = obs %>% filter(donor_id %in% viral_hits$donor_id) %>% 
  filter(clone_id!='') %>% 
  left_join(viral_hits %>% select(clone_id,hit)) %>% 
  mutate(annot=ifelse(!is.na(hit),'Viral','None'))

dat=dat %>% filter(
  clone_id %in% (dat %>% group_by(clone_id) %>% tally() %>% filter(n>1) %>% pull(clone_id))
)

dat %>% 
  ggplot(aes(log10_counts,Nonviral))+
  facet_grid(~annot)+
  geom_density_2d_filled(contour_var = "ndensity", bins=30, contour = F)+
  theme(legend.position = 'none')

```

## S7G

```{r fig.height=3, fig.width=5}

dat = obs %>% select(donor_id,pheno,Nonviral) %>% drop_na() %>% 
  left_join(labels2) %>% mutate(pheno=labels2) %>% 
  group_by(donor_id,pheno) %>% 
  summarise(Nonviral=mean(Nonviral))
  
pheno.order = dat %>% group_by(pheno) %>% 
  summarise(m=median(Nonviral)) %>% arrange(-m) %>% pull(pheno)

dat %>% 
  mutate(pheno=factor(pheno,rev(pheno.order))) %>% 
  ggplot(aes(pheno,Nonviral,fill=pheno))+
  geom_boxplot(outlier.alpha=0)+
  #geom_jitter(width=0.2,height=0,size=0.2,alpha=0.2)+
  scale_fill_manual(values=Tcell_pheno_colors)+
  labs(y='Mean non-viral score')+
  theme(legend.position = 'none',axis.title.x = element_blank(), 
    axis.text.x = element_text(angle = 45, vjust = 1, hjust=1, size=11)) -> pl
pl
ggsave(plot=pl,filename = '../figures/S7/G.pdf',width=5,height=3, dpi="retina")

```

## 












































