---
title: "S9"
output:
  html_document:
    code_folding: hide
    toc: true # table of content true
    toc_depth: 3  # upto three depths of headings (specified by #, ## and ###)
    number_sections: false  ## if you want number sections at each table header
params:
    args: myarg
---

## Setup

```{r setup-import, eval=T, hide=T}
library(tidyverse)
library(ggpubr)
library(RColorBrewer)
library(viridis)
source('../resources/aes.R')
range01 <- function(x){(x-min(x))/(max(x)-min(x))}
load(file = '../preprocessing/data/comp.RData')
load(file = '../preprocessing/data/ords.RData')
load(file = '../preprocessing/data/tcr_analysis.RData')
obs = read.csv('../preprocessing/data/Tcell_obs.csv')
tcr = read.csv('../preprocessing/data/import/Tcell-scTCR.csv')
donor_md = read.csv('../preprocessing/data/import/metadata-donor.csv')
dir.create('../figures/S9')
```

## A

```{r fig.height=2.5, fig.width=2.5}

dat = read_csv('../resources/neoantigen_predictions.csv')

dat %>% arrange(-score) %>% group_by(epitope) %>% slice_head(n=1) %>% 
  ggplot(aes(score))+geom_histogram(bins = 50)+
  labs(x='Prediction score',y='Count')+
  geom_vline(xintercept = 0.7, color='red')+
  scale_y_continuous(breaks=c(0,4,8,12))+
  theme(axis.text.x = element_text(size=11),axis.title.x = element_text(size=13),
    axis.text.y = element_text(size=11),axis.title.y = element_text(size=13))->pl
pl
ggsave(plot=pl,filename = paste0('../figures/S9/A-left.pdf'),height=2.5,width=2.5,dpi="retina")

```

```{r fig.height=3.5, fig.width=5.5}

dat = read_csv('../resources/neoantigen_predictions.csv') %>% 
  arrange(-score) %>% group_by(epitope) %>% slice_head(n=1) %>% ungroup()

dat.pl = obs %>% filter(donor_id %in% dat$donor_id) %>% 
  left_join(
    tcr[tcr$chain=='TRB',] %>% select(clone_id,CDR3aa) %>% distinct()
  ) %>% 
  left_join(dat %>% select(donor_id,CDR3aa_beta,score), 
    by=c('donor_id'='donor_id','CDR3aa'='CDR3aa_beta')) %>% 
  filter(!is.na(score))

dat.exp = dat.pl %>% group_by(CDR3aa) %>% tally() %>% filter(n>1) %>% pull(CDR3aa)

dat.pl %>% filter(CDR3aa %in% dat.exp) %>% 
  group_by(donor_id,CDR3aa,pheno) %>% tally() %>% 
  ggplot(aes(n,CDR3aa,fill=pheno))+facet_grid(donor_id~.,space='free',scales='free')+
  geom_col(color='black')+scale_fill_manual(values = Tcell_pheno_colors)+
  labs(x='N cells',y='Clone')+
  theme(
    axis.text.y = element_blank(),axis.ticks.y=element_blank(),
    legend.key.size = unit(0.5, "cm"),legend.title=element_blank(),legend.text=element_text(size=9),
    strip.text.y = element_text(angle = 0), panel.background = element_blank()
  )->pl
pl
ggsave(plot=pl,filename = paste0('../figures/S9/A-right.pdf'),height=3.5,width=5.5,dpi="retina")

```



## B

```{r fig.width=3, fig.height=3, eval=T, hide=T}

mhc.path = c("Interferon/MHC-II (I)","Interferon/MHC-II (II)")

read_csv('../preprocessing/data/Nonviral_tumour_modules.csv') %>% 
  ggplot(aes(r,-log10(fdr)))+
  geom_point(data = . %>% filter(fdr>=0.1), color='grey70')+
  geom_point(data = . %>% filter(fdr<0.1), color=diagnosis_col['MM'])+
  geom_point(data = . %>% filter(fdr<0.1 | pathway %in% mhc.path), shape=21)+
  ggrepel::geom_text_repel(data = . %>% filter(fdr<0.1 | pathway %in% mhc.path), 
    aes(label=pathway),size=3.5)+
  geom_hline(yintercept = -log10(0.1), linetype='dotted', linewidth=0.5)+
  labs(x='Correlation with non-viral score', y='-log10 FDR')+
  theme_classic() ->pl
pl
#ggsave(plot=pl,filename = 'figures/TRT/vln-nonvir_TumMod.pdf',height=2.5,width=2.5, dpi="retina")

```

## C

```{r S9C, fig.height=4, fig.width=6, eval=T, hide=T}
tumour_DE = read.csv('../preprocessing/data/tumour_DE.csv',row.names=1)
load(file='../preprocessing/data/tumour_DE_fgsea.RData')

# Top DEP dotplot
#fgseas %>% group_by(pathway,de) %>% tally() %>% arrange(desc(de),-n) #manually select

shared.in = read.csv('../resources/Fig-S9C.csv')
sig.pl = shared.in$pathway
name.pl = shared.in$name_pl

fgseas %>%
  filter(pathway %in% sig.pl, NES>0) %>%
  left_join(shared.in) %>% 
  mutate(name_pl=factor(name_pl,rev(name.pl))) %>% 
  filter(!is.na(name_pl)) %>% 
  ggplot(aes(donor_id,name_pl,fill=NES, size=-log10(padj)))+geom_point(shape=21)+
  scale_y_discrete(label = function(x) stringr::str_trunc(x, 50))+
  scale_fill_gradient2(low='dodgerblue',mid='white',high='red')+
  scale_size_continuous(range = c(0.5,5))+
  labs(x='Patient',
    fill='Normalised\nenrichment\nrelative to\nnormal PC', size='-log10 FDR')+
  coord_fixed()+
  theme(
    plot.title = element_text(hjust = 0.5, size=11),
    axis.text.x=element_blank(),axis.ticks.x=element_blank(),
    axis.title.y=element_blank(), 
    axis.line=element_blank(), panel.border = element_rect(colour = "black", fill=NA, size=1)
  )->pl
pl
#ggsave(plot=pl,filename = paste0('../figures/S9/C.pdf'),height=4,width=6,dpi="retina")

```

